<?php
return [
  [
    "src" => "./images/help-ukrainiars/photo1.png",

    "title" => [
      'ukr' => 'Проєкт "Я серед своїх"',
      'en' => '"I am among my own" project'
    ],
    "texts" => [
      [
        "text" => [
          'ukr' => " Реалізований у партнерстві з ALPS Resilience проєкт мав на
                      меті сприяння в реінтеграції та адаптації дітей, що
                      поверталися до своїх громад або стали
                      внутрішньо-переміщеними внаслідок війни в Україні. Команда
                      Скаутів України навчила понад 100 дорослих лідерів з
                      Житомирської, Чернігівської, Сумської та Київської
                      областей задля відкриття нових Скаутських груп на базі
                      шкіл, будинків творчості та молодіжних центрів для понад
                      750 дітей та забезпечила їх матеріалами для активностей.
                      Також проєктом було передбачено проведення інтерактивних
                      ігрових програм, і більш ніж 4500 дітей змогли зануритись
                      в атмосферу дитинства, гри та у незвичній формі
                      познайомитись зі Скаутингом, що було спрямовано на
                      зміцнення їхньої психологічної стійкості та сприяння
                      адаптації в нових умовах.",
          'en' => "Implemented in partnership with ALPS Resilience,
           the project aimed to facilitate the reintegration and adaptation
            of children who returned to their communities or were internally displaced 
            as a result of the war in Ukraine. The Scouts of Ukraine team trained more
             than 100 adult leaders from Zhytomyr, Chernihiv, Sumy and Kyiv regions
              to open new Scout groups in schools, houses of creativity and youth
               centres for more than 750 children and provided them with activity materials.
                The project also included interactive game programmes, and more than 4,500 children 
                were able to immerse themselves in the atmosphere of childhood,
                 play and get to know Scouting in an unusual way, which was aimed 
                 at strengthening their psychological resilience and helping
                  them adapt to new conditions.
"
        ],
      ],
    ],
  ],
  [
    "src" => "./images/help-ukrainiars/photo2.jpeg",

    "title" => [
      'ukr' => 'Проєкт "Emergency Response"',
      'en' => '"Emergency Response" project'
    ],
    "texts" => [
      [
        "text" => [
          'ukr' => 'В рамках проекту "Emergency Response", Скаути України були
                      залучені до надання екстреної допомоги у перші місяці
                      війни, координуючи зусилля на місцевому та міжнародному
                      рівнях. За кілька перших місяців війни Всесвітня
                      Організація Скаутського Руху (ВОСР) зібрала для допомоги
                      Україні понад 700.000 доларів. Завдяки зборам коштів наших
                      партнерів та друзів у Скаутингу, ми надали допомогу понад
                      100.000 українців як в Україні, так і за кордоном.',
          'en' => "Within the framework of the Emergency Response project,
           the Scouts of Ukraine were involved in providing emergency assistance
            in the first months of the war, coordinating efforts at the local
             and international levels. In the first few months of the war, 
             the World Organization of the Scout Movement (WOSM) raised more
              than $700,000 to help Ukraine. Thanks to the fundraising efforts 
              of our partners and friends in Scouting, we have provided assistance
               to more than 100,000 Ukrainians both in Ukraine and abroad.
"
        ],
      ],
    ],
  ],
  [
    "src" => "./images/help-ukrainiars/photo3.JPG",

    "title" => [
      'ukr' => '"Проєкт "UAct"',
      'en' => '"The UAct" project'
    ],
    "texts" => [
      [
        "text" => [
          'ukr' => "Реалізований у співпраці з Дитячим фондом ООН, ЮНІСЕФ,
                      проєкт був спрямований на допомогу дітям та їхнім сім'ям,
                      які були змушені покинути свої домівки. Заходи проєкту
                      включали психологічну підтримку, освітні програми та
                      допомогу у забезпеченні базових потреб, дозволяючи дітям
                      продовжувати навчання та отримувати підтримку в нових
                      умовах. Діти мали змогу долучитися до діяльності
                      Скаутських груп у нових місцях проживання, таким чином
                      маючи можливість знайти нових друзів та легше
                      соціалізуватися у незнайомих умовах.",
          'en' => "Implemented in cooperation with the United Nations Children's Fund,
           UNICEF, the project was aimed at helping children and their families
            who were forced to leave their homes. Project activities included psychological
             support, educational programmes, and assistance with basic needs, 
             enabling children to continue their education and receive support
              in the new environment. The children were able to join Scout groups 
              in their new places of residence, thus having the opportunity to make 
              new friends and socialise more easily in unfamiliar environments.
"
        ],
      ],
    ],
  ],
  [
    "src" => "./images/help-ukrainiars/photo4.JPG",

    "title" => [
      'ukr' => ' Проєкт "Скаути для України"',
      'en' => "‘Scouts for Ukraine’ project
"
    ],
    "texts" => [
      [
        "text" => [
          'ukr' => "Цей проєкт відбувся на самому початку війни у 2014 році і
                      був зосереджений на наданні допомоги
                      внутрішньо-переміщеним особам з Донецької та Луганської
                      областей, а також АР Крим. У рамках проєкту Скаути
                      забезпечували родини ВПО продуктами харчування, медичними
                      препаратами, одягом, а також підтримували їх в пошуку
                      тимчасового житла. Діти цих родин мали змогу приєднатися
                      до Скаутських груп у їхніх нових місцях проживання та
                      знайти нових друзів.",
          'en' => "This project took place at the very beginning of the war
           in 2014 and focused on providing assistance to internally displaced
            persons from Donetsk and Luhansk oblasts, as well as
             the Autonomous Republic of Crimea. As part of the project, 
             the Scouts provided IDP families with food, medicines, and clothing, 
             and supported them in finding temporary housing. The children of these
              families were able to join Scout groups in their new places
               of residence and make new friends.
"
        ],
      ],
    ],
  ],
];