<?php
return [

  "main-title" => [
    'ukr' => "Допомога українцям",
    'en' => "Helping Ukrainians
",
  ],
  "main-text" => [
    'ukr' => "Із самого початку Скаути України відіграють велику роль у
              підтримці українського суспільства шляхом проєктної діяльності,
              використовуючи Скаутські принципи. Ми проводимо проєкти різної
              направленості, щоб максимально використати наш вплив та
              допомогти українському народу в цей складний час.",
    'en' => "From the very beginning, Scouts of Ukraine have played
     a major role in supporting Ukrainian society through project activities
      using Scouting principles. We run projects of various kinds to maximise
       our influence and help the Ukrainian people in this difficult time.",
  ],
  
  
  "volunteering-text-part-first" => [
    'ukr' => "Кожен проект, який Скаути України втілили в життя під час війни,
                    мав одну мету — полегшити життя тих, хто постраждав від війни,
                    та надати їм необхідну підтримку.",
    'en' => "Every project implemented by the Scouts of Ukraine during the war
     had one goal: to make life easier for those affected by the war and provide 
     them with the necessary support.",
  ],
  "volunteering-text-part-second" => [
    'ukr' => 'Якщо ви хочете допомогти нам у нашій місії, натисніть кнопку
                    "Задонатити" та зробіть свій внесок сьогодні. Ваша допомога може
                    змінити життя людей на краще, принести надію та підтримку в ці
                    важкі часи. Вона також підтримає наших Скаутів, показавши, що
                    їхня робота недаремна.',
    'en' => "If you would like to help us in our mission,
     please click the Donate button and make your contribution today.
      Your help can change people's lives for the better, bringing hope
       and support in these difficult times. It will also support our Scouts,
        showing that their work is not in vain.",
  ],
  "volunteering-text-part-third" => [
    'ukr' => "Наша робота була можлива завдяки щедрості наших міжнародних та
                українських донорів та невтомній праці наших Скаутів-волонтерів.
                Нині ми продовжуємо шукати підтримку наших ініціатив, щоб і
                надалі надавати допомогу тим, хто її потребує. Кожен ваш внесок
                має значення.",
    'en' => "If you would like to help us in our mission, please click the
     Donate button and make your contribution today. Your help can change people's
      lives for the better, bringing hope and support in these difficult times.
       It will also support our Scouts, showing that their work is not in vain.
       Our work has been made possible by the generosity of our international
        and Ukrainian donors and the tireless work of our volunteer Scouts.
         Today, we continue to seek support for our initiatives so that we can continue
          to help those in need. Every contribution makes a difference!
",
  ],
  "donation-btn" => [
    'ukr' => "Задонатити",
    'en' => "Donate",
  ],
];
