<?php
return [
  [
    'header' => [
      'en' => 'About Us',
      'ukr' => 'Про нас'
    ],
    'links' => [
      [
        'link' => './our-history',
        'title' => [
          'en' => 'Eng Наша історія',
          'ukr' => 'Наша історія'
        ]
      ],
      [
        'link' => './our-mission',
        'title' => [
          'en' => ' enng Наша місія',
          'ukr' => 'Наша місія'
        ]
      ],
      [
        'link' => './scout-method',
        'title' => [
          'en' => 'Eng Скаутський Метод',
          'ukr' => 'Скаутський Метод'
        ]
      ],
      [
        'link' => './our-team',
        'title' => [
          'en' => 'Our Team',
          'ukr' => 'Команда'
        ]
      ]
    ]
  ],

  [
    'header' => [
      'en' => 'Eng Діяльність',
      'ukr' => 'Діяльність'
    ],
    'links' => [
      [
        'link' => './our-mission#our-program',
        'title' => [
          'en' => 'Eng Наша програма',
          'ukr' => 'Наша програма'
        ]
      ],
      [
        'link' => './help-ukrainians',
        'title' => [
          'en' => 'eng Проєкти',
          'ukr' => 'Проєкти'
        ]
      ],
      [
        'link' => './our-events',
        'title' => [
          'en' => 'Eng Заходи',
          'ukr' => 'Заходи'
        ]
      ]
    ]
  ],
  [
    'header' => [
      'en' => 'E Всесвітній Скаутинг',
      'ukr' => 'Всесвітній Скаутинг'
    ],
    'links' => [
      [
        'link' => './world-scouting',
        'title' => [
          'en' => 'Eng ВОСР',
          'ukr' => 'ВОСР'
        ]
      ],
      [
        'link' => './scouting-history',
        'title' => [
          'en' => 'enng Історія Скаутингу',
          'ukr' => 'Історія Скаутингу'
        ]
      ]
    ]
  ]
];
