

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-YQ6LLZPXMY"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() { dataLayer.push(arguments); }
      gtag('js', new Date());

      gtag('config', 'G-YQ6LLZPXMY');
    </script>
    <link rel="canonical" href="https://ukrscout.org/"/>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="title" content="<?=getValue($texts,"meta-title")?>"/>
    <meta name="description"
      content="<?=getValue($texts, 'meta-description')?>">
    <title><?=getValue($texts, "page-title")?></title>
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@600;700&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="./common.css"/>
    <link rel="stylesheet" href="./regular-block.css"/>
    <link rel="icon" href="./favicon.ico" type="image/icon type">
  
