<?php
return [
  [
    "text" => [
      'ua' => " Тобі від 18 до 22 років і ти хочеш продовжити свої пригоди у
              Cкаутингу? Ровери - енергійні дослідники та активні члени
              суспільства, які беруть участь у проєктній діяльності,
              служінні громаді та міжнародних подіях для цього віку. ",
      'en' => "Are you between 18 and 22 years old and want to continue
       your Scout adventures? Rovers are energetic explorers and active
        members of society who participate in project activities, community
         service and international events for this age."
    ]
  ],
  [
    "text" => [
      'ua' => " Цей етап Скаутингу покликаний запропонувати тобі більшу
              незалежність, що дозволить тобі керувати проєктами,
              організовувати заходи та змінювати свою спільноту на краще.
              Роверство - це можливість взяти на себе ініціативу та стати
              частиною команди однолітків. Разом ви формуєте команди,
              розвиваєтеся як лідери, втілюєте в життя захоплюючі проєкти та
              вчитеся відповідальності через реальні дії. ",
      'en' => "This stage of Scouting is designed to offer you greater independence,
       allowing you to manage projects, organize events and change your community for 
       the better. Scouting is an opportunity to take initiative and become part of
        a peer team. Together you build teams, develop as leaders, bring exciting 
        projects to life and learn responsibility through real action."
    ]
  ],
  [
    "text" => [
      'ua' => " Приєднуйся та розпочинай свою Скаутську подорож, де твоя
              пристрасть та енергія можуть стати в пригоді як тобі, так і
              твоїй громаді.",
      'en' => "Join and start your Scouting journey, where your passion
       and energy can benefit both you and your community.
"
    ]
  ],

];
