<?php
return [
  [
    "src" => "/images/join-us/advantages/img1.png",
    "title" => [
      'ua' => "Особистісний розвиток:",
      'en' => 'Personal development:'
    ],
    "text" => [
      'ua' => " Скаутинг заохочує культуру безперервного розвитку, заохочуючи
            членів організації здобувати нові навички та знання на кожному
            етапі їхнього життя. Скаути набувають впевненості в собі та
            відчувають себе успішними завдяки різноманітним видам
            діяльності, прийняттю викликів та досягненню особистих цілей.
            Скаутинг дає безліч напрямків для саморозвитку, тому в
            Скаутському Русі ніколи не буває нудно.",
      'en' => "Scouting promotes a culture of continuous development,
       encouraging members to acquire new skills and knowledge at every
        stage of their lives. Scouts gain self-confidence and a sense of 
        accomplishment through a variety of activities, taking on challenges
         and achieving personal goals. Scouting provides many directions for self-development, 
         so there is never a dull moment in Scouting."
    ],
  ],
  [
    "src" => "/images/join-us/advantages/img2.png",
    "title" => [
      'ua' => "Залучення у громаду:",
      'en' => 'Involvement in the community:'
    ],
    "text" => [
      'ua' => "Скаути відомі своєю відданістю суспільній роботі, участю в
            проєктах та ініціативах, які реально змінюють життя в їхніх
            громадах. Завдяки цим діям вони розвивають сильне почуття
            соціальної відповідальності та відчувають радість від того, що
            допомагають іншим.",
      'en' => "Scouts are known for their commitment to community service, 
      participating in projects and initiatives that make a real difference
       in the lives of their communities. Through these actions, they develop
        a strong sense of social responsibility and experience the joy of helping others."
    ],
  ],
  [
    "src" => "/images/join-us/advantages/img3.png",
    "title" => [
      'ua' => "Міжнародний досвід:",
      'en' => 'International experience:'
    ],
    "text" => [
      'ua' => "Скаутинг пропонує усім учасникам Руху можливість брати участь
            у міжнародних заходах різного формату. Цей досвід дозволяє
            Скаутам набувати унікального досвіду, розуміти різні культури
            та будувати міжнародну дружбу, розширюючи свій світогляд.",
      'en' => "Scouting offers all members of the Movement the opportunity to 
      participate in international events of various formats. This experience 
      allows Scouts to gain unique experiences, understand different cultures,
       and build international friendships, broadening their worldview."
    ],
  ],
  [
    "src" => "/images/join-us/advantages/img4.png",
    "title" => [
      'ua' => "Дружба та нетворкінг:",
      'en' => 'Friendship and networking:'
    ],
    "text" => [
      'ua' => "Скаутинг - це можливість знайти дружбу на все життя. Цей Рух
            надає людям простір для спілкування та обміну досвідом,
            сприяючи формуванню середовища взаємної поваги та розуміння. І
            дорослі, і молоді люди знаходять у Скаутингу нові знайомства,
            які залишаються з ними на все життя.",
      'en' => "Scouting is an opportunity to make lifelong friendships.
 This Movement provides space for people to communicate and
  share experiences, contributing to the formation of an environment 
  of mutual respect and understanding. Both adults and young people find 
  new acquaintances in Scouting that stay with them for life."
    ],
  ],
  [
    "src" => "/images/join-us/advantages/img5.png",
    "title" => [
      'ua' => "Пригоди на свіжому повітрі:",
      'en' => 'Outdoor adventures:'
    ],
    "text" => [
      'ua' => "Скаути регулярно взаємодіють з природою, вчаться дбайливому
            ставленню до довкілля та навичкам виживання. Ця діяльність не
            лише приносить радість і досвід, але й розвиває глибоку повагу
            до природи та її збереження. Більше того, це викликає у
            Скаутів бажання відірватися від своїх гаджетів і отримати
            насолоду від активностей на свіжому повітрі.",
      'en' => "Scouts regularly interact with nature, and learn environmental 
care and survival skills. This activity not only brings joy and
experience but also develops a deep respect for nature and its
 preservation. What's more, it makes Scouts want to get away from 
 their gadgets and enjoy outdoor activities"
    ],
  ],
  [
    "src" => "/images/join-us/advantages/img6.png",
    "title" => [
      'ua' => "Розвиток лідерських якостей:",
      'en' => 'Development of leadership qualities:'
    ],
    "text" => [
      'ua' => "Учасники різного віку можуть брати на себе лідерські ролі не
            лише у своїй Скаутській групі, але й на національному та
            міжнародному рівнях: керувати проєктами, вести за собою
            команди та брати участь у процесах прийняття рішень. Це дає
            кожному можливість стати ефективним лідером у своєму житті
            поза Скаутським Рухом.",
      'en' => "Members of all ages can take on leadership roles not only 
in their Scout group but also at the national and international levels:
managing projects, leading teams, and participating in decision-making processes.
 This gives everyone the opportunity to become an effective leader 
 in their life outside of Scouting."
    ],
  ],
  
];