<?php
return [
  [
    "text" => [
      'ukr' => " Тобі ще не виповнилося 18 років? Ти прагнеш досліджувати світ,
                  здобувати нові навички та знайти справжніх друзів? ",
      'en' => "Are you under 18? Do you want to explore the world, learn 
      new skills, and make real friends?"
    ]
  ],
  [
    "text" => [
      'ukr' => "  Національна Організація Скаутів України (НОСУ) запрошує дітей
                  та молодих людей вирушити у незабутню подорож особистісного
                  розвитку, пригод та веселощів, приєднавшись до нашої
                  Скаутської родини. ",
      'en' => "The National Organization of Scouts of Ukraine (NOSU) invites
       children and young people to embark on an unforgettable journey of
        personal development, adventure, and fun by joining our Scout family."
    ]
  ],
  [
    "text" => [
      'ukr' => " Як Скаут ти станеш членом однієї із наших Скаутських груп в
                  твоєму місті. У кожній групі діє патрульна система, тобто всі
                  учасники працюють у малих групах. Ти можеш доєднатися до
                  існуючого патруля або створити новий разом зі своїми друзями.
                  Зазвичай група збирається разом від одного до двох разів на
                  тиждень.",
      'en' => "As a Scout, you will join one of our Scout groups in your city.
       Each group has a patrol system, that is, all participants work in small groups.
        You can join an existing patrol or create a new one with your friends.
         The group usually meets once or twice a week.
"
    ]
  ],
  [
    "text" => [
      'ukr' => " Приєднуйся до нас та відкрий спавжній світ яскравих пригод та
                  нових знайомств. Тисни на посилання та стань членом
                  найбільшого всесвітнього молодіжного Руху!",
      'en' => "Join us and discover an exciting world of bright
       adventures and new acquaintances. Click on the link and
        become a member of the largest worldwide youth Movement!"
    ]
  ],
];