<?php
return [
  "page-title" => [
    'ukr' => "Приєднатись до нас",
    'en' => "Join Us",
  ],

  "meta-title" => [
    'ukr' => "Приєднатись до нас",
    'en' => 'Join Us'
  ],
  "meta-description" => [
    'ukr' => "Приєднатись до нас.",
    'en' => 'Join Us.'
  ],
  "main-title" => [
    'ukr' => "Як приєднатись до нас",
    'en' => "How to join us
",
  ],
  "main-text" => [
    'ukr' => 'Ми завжди раді вітати нових членів у нашій Скаутській родині! У тебе
            є кілька шляхів, як приєднатися до нас:
            <span class="color-part">стати Скаутом</span>
            - це опція для дітей та молодих людей до 18 років;
            <span class="color-part">стати Ровером</span> - якщо ти у віці від
            18 до 22 років, або <span class="color-part">стати Лідером</span>,
            якщо тобі вже виповнилося 18 років, і ти хотів би працювати з дітьми
            або в організаційному управлінні Організації. <br/> Шукай детальний опис
            обох варіантів нижче.',
    'en' => 'We are always happy to welcome new members to our Scouting family!
     You have several ways to join us:<span class="color-part"> becoming a Scout </span> is an option for children
      and young people under 18;<span class="color-part"> become a Rover </span> - if you are between 18 and 22 years old, 
      or<span class="color-part"> become a Leader </span>  if you are already 18 years old and you would like to work with 
      children or in the organizational management.  <br/> Find a detailed description of both options below.
',
  ],
  "sub-title-first" => [
    'ukr' => "Стати Скаутом",
    'en' => "Become a Scout",
  ],
  "sub-title-second" => [
    'ukr' => "Стати Ровером",
    'en' => "Become a Rover",
  ],
  "join-btn" => [
    'ukr' => "Приєднатись до нас",
    'en' => "Join us",
  ],
  
  "advantages-title" => [
    'ukr' => "Переваги Скаутингу",
    'en' => "Advantages of Scouting",
  ],
  "sub-title-third" => [
    'ukr' => "Стати Скаут-Лідером",
    'en' => "Become a Scout Leader
",
  ],
  "leadership-text-title-first" => [
    'ukr' => "Робота з дітьми",
    'en' => "Work with children",  ],
  "leadership-text-title-second" => [
    'ukr' => "Робота в організаційному управлінні",
    'en' => "Work in organizational management",
  ],
  ];