<?php
return [
  [
    "text-management" => [
      'ua' => "Якщо ти прагнеш мати значний вплив на розвиток Скаутів
              України, працюючи за лаштунками, наші ролі в організаційному
              управлінні - ідеальна можливість для цього. Тут ти можеш
              застосувати свої навички в комунікації, маркетингу, створенні
              контенту, розробці стратегій, міжнародній діяльності тощо.
              Тобі не обов'язково бути експертом - ми вітаємо тих, хто має
              бажання вчитися та розвиватися.",
      'en' => "If you want to have a significant impact on the
       development of Scouts of Ukraine, working behind the scenes,
        our roles in organizational management are an ideal opportunity for this.
         Here you can apply your skills in communication, marketing, content creation,
          strategy development, international activities etc. You don't have to be an expert -
           we welcome those who are willing to learn and develop."
    ]
  ],
  [
    "text-management" => [
      'ua' => " У серці Скаутської Організації України ти зрозумієш, що
              збагачуючи життя інших, ти можеш, у свою чергу, збагатити своє
              власне, з підтримкою нашої відданої команди на кожному кроці
              цього шляху.",
      'en' => "At the heart of the Scouts of Ukraine Organization, 
      you will understand that by enriching the lives of others, you can, 
      in turn, enrich your own, with the support of our dedicated team 
      every step of the way."
    ]
  ],
];