<?php
return [
  [
    "text" => [
      'ukr' => " Скаутинг не лише для молодих людей, дорослі відіграють життєво
              важливу роль в успіху та зростанні нашої Організації. ",
      'en' => "Scouting is not just for young people: adults also
       play a vital role in the success and growth of our Organization."
    ]
  ],
  [
    "text" => [
      'ukr' => "Відчуваєш в собі лідерські якості? Хочеш продовжувати
              розвиватися та допомагати у розвитку молодого покоління? 
              Прагнеш змінити на краще життя молоді та своєї громади? ",
      'en' => "Do you feel leadership qualities in yourself? Do you want 
      to continue to develop and help in the development of the younger 
      generation? Do you want to change the lives of young people and your community for the better?"
    ]
  ],
  [
    "text" => [
      'ukr' => "Скаути України шукають відданих своєму покликанню дорослих,
              які приєднаються до наших лав в якости Скаутських лідерів та
              волонтерів загального профілю, аби допомогти формувати
              майбутнє нашої Організації та надихати наступне покоління
              лідерів та інноваторів.",
      'en' => "Scouts of Ukraine are looking for dedicated adults 
      to join our ranks as Scout leaders as well as general volunteers 
      to help shape the future of our Organization and inspire the next
       generation of leaders and innovators"
    ]
  ],
  [
    "text" => [
      'ukr' => "Існують два основні способи, якими ти можеш зробити свій
              внесок у розвиток Скаутів України (читай нижче про обидва). ",
      'en' => "There are two main ways in which you can contribute to the
       development of Scouts of Ukraine (read below about both)."
    ]
  ],
 

];
