<?php
return [
  [
    "text-work-children" => [
      'ukr' => "  Як Скаутський лідер, ти будеш працювати безпосередньо з
              дітьми, забезпечуючи наставництво впродовж їхньої Cкаутської
              подорожі. Ти станеш рушієм їхнього розвитку та будеш
              споглядати їх становлення як впевнених та самостійних членів
              суспільства.",
      'en' => "As a Scout Leader, you will work directly with children,
       providing mentorship throughout their Scouting journey. 
       You will become the driver of their development and you will
        watch their formation as confident and independent members of society."
    ]
  ],
  [
    "text-work-children" => [
      'ukr' => " Ця роль чудово підходить тим, хто вже займається освітою чи
              роботою з молоддю, хоча такий досвід не є обов'язковим. Ми
              надаємо постійну підтримку та ресурси для того, щоб ти міг
              проводити заняття впевнено та творчо, роблячи кожну активність
              сходинкою на шляху до всебічного розвитку Скаутів та тебе
              самого.",
      'en' => "This role is ideal for those with previous experience
       in education or youth work, although such experience is not essential.
        We provide ongoing support and resources so that you can run Scout meetings
         confidently and creatively, making each activity a stepping stone towards
          the all-round development of Scouts and yourself."
    ]
  ],
 
];