<?php
return [
  "page-title" => [
    'ukr' => "Наша команда",
    'en' => "Our team",
  ],

  "meta-title" => [
    'ukr' => "Наша команда",
    'en' => 'Our team'
  ],
  "meta-description" => [
    'ukr' => "Наша команда.",
    'en' => 'Our team.'
  ],
  "main-title" => [
    'ukr' => "Наша Команда",
    'en' => "Our team 
",
  ],
  "main-text" => [
    'ukr' => "Дякуємо вам за підтримку та віру в нас.
     Ми робимо все, щоб розвивати Скаутинг в рідній країні 
     та знаходити нових партнерів в інших.
",
    'en' => "Thank you for your support and faith in us.
     We do our best to develop Scouting in our home country
      and find new partners in other countries.",
  ],
 
];
