<?php
return [

  [
    "src" => "/images/our-team/chernyshova.jpg",

    "style" => "",
    "display" => '',

    "name" => [
      'ua' => "Аліна Чернишова",
      'en' => 'Alina Chernyshova'
    ],
    "position" => [
      'ua' => "Голова Національної Ради",
      'en' => 'Head of the National Board'
    ],
   
  ],

  [
    "src" => "/images/our-team/kyslytsia.jpg",

    "style" => "",
    "display" => '',

    "name" => [
      'ua' => "Анастасія Кислиця",
      'en' => 'Anastasiia Kyslytsia'
    ],
    "position" => [
      'ua' => "Заступниця Голови Національної Ради",
      'en' => 'Deputy Head of the National Board'
    ],
   
  ],

  [
    "src" => "/images/our-team/sapiha.jpg",

    "style" => "",
    "display" => '',

    "name" => [
      'ua' => "Світлана Сапіга",
      'en' => 'Svitlana Sapiga'
    ],
    "position" => [
      'ua' => "Членкиня Національної Ради",
      'en' => 'Member of the National Board'
    ],
   
  ],

  [
    "src" => "/images/our-team/slepchenko.jpg",

    "style" => "",
    "display" => '',

    "name" => [
      'ua' => "Анна Слепченко",
      'en' => 'Anna Slepchenko'
    ],
    "position" => [
      'ua' => "Членкиня Національної Ради",
      'en' => 'Member of the National Board'
    ],
   
  ],

  [
    "src" => "/images/our-team/tsehmaistrenko.jpg",

    "style" => "",
    "display" => '',

    "name" => [
      'ua' => "Юлія Цехмайстренко",
      'en' => 'Yulia Tsekhmaistrenko'
    ],
    "position" => [
      'ua' => "Членкиня Національної Ради",
      'en' => 'Member of the National Board'
    ],
   
  ],

  // [
  //   "src" => "/images/our-team/10.png",

  //   "style" => "",
  //   "display" => 'style="display: none;',

  //   "name" => [
  //     'ua' => "Ольга Дибкалюк",
  //     'en' => ''
  //   ],
  //   "position" => [
  //     'ua' => "Міжнародна Комісарка",
  //     'en' => ''
  //   ],
   
  // ],


  // [
  //   "src" => "/images/our-team/11.png",

  //   "style" => "member-position-not-transform",
  //   "display" => 'style="display: none;',

  //   "name" => [
  //     'ua' => "Олександра Картвелішвілі",
  //     'en' => ''
  //   ],
  //   "position" => [
  //     'ua' => " Координаторка з європейської інтеграції та стратегічних
  //             зв’язків",
  //     'en' => ''
  //   ],
   
  // ],
  [
    "src" => "/images/our-team/puhachova.jpg",

    "style" => "",
    "display" => '',

    "name" => [
      'ua' => "Віолетта Пугачова",
      'en' => 'Violetta Puhachova'
    ],
    "position" => [
      'ua' => "Голова Ревізійної комісії",
      'en' => 'Head of the Audit Committee'
    ],
   
  ],

  [
    "src" => "/images/our-team/fursova.jpg",

    "style" => "",
    "display" => '',

    "name" => [
      'ua' => "Юлія <br> Фурсова",
      'en' => 'Yuliia <br> Fursova'
    ],
    "position" => [
      'ua' => "",
      'en' => 'Member of the Audit Committee'
    ],
   
  ],

  [
    "src" => "/images/our-team/kolobova.jpg",

    "style" => "",
    "display" => '',

    "name" => [
      'ua' => "Ярослава Колобова",
      'en' => 'Yaroslava Kolobova'
    ],
    "position" => [
      'ua' => "Членкиня Ревізійної комісії",
      'en' => 'Member of the Audit Committee'
    ],
   
  ],
];