<?php
return [
  [
    "title" => [
      "ua" => "Діяльність",
      "en" => "Activities",
    ],
    "links" => [
      [
        "url" => "/our-mission",
        "text" => [
          "ua" => "Наша програма",
          "en" => "Programme",
        ],
      ],
      [
        "url" => "/help-ukrainians",
        "text" => [
          "ua" => "Наші проєкти",
          "en" => "Projects",
        ],
      ],
    ]
  ],

  [
    "title" => [
      "ua" => "Про Нас",
      "en" => "About us",
    ],
    "links" => [
      [
        "url" => "/our-history",
        "text" => [
          "ua" => "Історія",
          "en" => "History",
        ],
      ],
      [
        "url" => "/scout-method",
        "text" => [
          "ua" => "Скаутський Метод",
          "en" => "Method",
        ],
      ],
      [
        "url" => "/our-team",
        "text" => [
          "ua" => "Команда",
          "en" => "Team",
        ],
      ],
    ]
  ],
  [
    "title" => [
      "ua" => "Долучитись",
      "en" => "Join us",
    ],
    "links" => [
      [
        "url" => "/join-us",
        "text" => [
          "ua" => "Стати Скаутом",
          "en" => "Become a Scout",
        ],
      ],
      [
        "url" => "/join-us#scout-leader",
        "text" => [
          "ua" => "Стати Лідером",
          "en" => "Become a Scout-Leader",
        ],
      ],
      [
        "url" => "/donation",
        "text" => [
          "ua" => "Допомога організації",
          "en" => "Supporting the organization",
        ],
        "hidden" => true,
      ],
    ]
  ],
];
