<?php
return [
  'logo' =>  [
    'en' => 'icon-logo_footer_en',
    'ukr' => 'logo-footer'
  ],
  "questions" => [
    "ukr" => "Маєш питання або пропозиції? Ми завжди відкриті для спілкування. Пиши
      нам на",
    "en" => "Any questions or suggestions? We're keen to hear them! Email us at ",
  ],
  "sign" => [
    "ukr" => "Підпишіться на нас у соціальних мережах",
    "en" => "Follow us on social media!",
  ],
];
