<?php
return [
  "page-title" => [
    'ukr' => "Історія Скаутингу",
    'en' => "History of Scouting",
  ],

  "meta-title" => [
    'ukr' => "Історія Скаутингу",
    'en' => 'History of Scouting'
  ],
  "meta-description" => [
    'ukr' => "Історія Скаутингу.",
    'en' => 'History of Scouting.'
  ],
  "main-title" => [
    'ukr' => "Історія Скаутингу",
    'en' => "History of Scouting",
  ],
  "additional-text" => [
    'ukr' => "Історія Скаутингу",
    'en' => "Want to know more about the history of Scouts of Ukraine?",
  ],
  "additional-link" => [
    'ukr' => "Історія Скаутингу",
    'en' => " Follow this link!",
  ],
  
  
];
