<?php
return [

  [
    "src" => "./images/scouting-history/photo1.jpg",
    "dates" => "1907 – 1908",
    "title" => [
      'ukr' => "Ранні роки",
      'en' => 'Early Beginnings'
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => "Скаутинг розпочався як програма для хлопчиків віком
                    від 11 до 18 років.",
        'en' => "Scouting began as a programme for boys aged 11 to 18."
      ],
     ] ,
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1907:</span> Перший
                    експериментальний табір, організований Робертом Бейден-Поуеллом
                    з 20 хлопчиками на острові Браунсі, Велика Британія, мав великий
                    успіх.',
        'en' => '<span class="regular-block-text-bold">1907:</span> The first experimental camp organized by
         Robert Baden-Powell with 20 boys at Brownsea Island,
          United Kingdom was a great success.'
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">1908:</span> Бейден-Поеулл
                    опублікував книгу “Скаутинг для хлопчиків”, яка одразу ж стала
                    відомою і з того часу була продана накладом понад 100 мільйонів
                    примірників.',
        'en' => '<span class="regular-block-text-bold">1908:</span> Baden-Powell published
         “Scouting for Boys”, which was an immediate hit and has since sold over 100 million copies.'
      ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo2.jpg",
    "dates" => "1909 – 1918",
    "title" => [
      'ukr' => "Розширення Скаутського Руху",
      'en' => 'Expansion of the Scout Movement'
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1909:</span> “Скаутинг для
                хлопчиків” був перекладений п’ятьма мовами. Це породило Рух,
                який швидко взяв назву “Бойскаути”.',
        'en' => '<span class="regular-block-text-bold">1909:</span> "Scouting for Boys" 
        was translated into five languages. It produced a Movement that quickly 
        adopted the name “The Boy Scouts”.'
      ],
     ] ,
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1909:</span> Скаутський зліт у
                Лондоні зібрав понад 11 000 Скаутів.',
        'en' => '<span class="regular-block-text-bold">1909:</span> A Scout rally in London attracted more than 11,000 Scouts.'
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">1910:</span> Бейден-Поеулл
                заснував Організацію для дівчат-Гайдів під керівництвом своєї
                сестри Агнес.',
        'en' => '<span class="regular-block-text-bold">1910:</span> Baden-Powell 
        started the Girl Guides under the leadership of his sister, Agnes.'
      ],
    ],
    [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1914:</span> Система Патрулів
                була створена для забезпечення стабільности Скаутингу під час
                Першої світової війни, оскільки Патрульні Лідери були
                добровольцями, які замінили дорослих лідерів.',
        'en' => '<span class="regular-block-text-bold">1914: </span> After the outbreak
         of World War I, the Patrol System proved highly effective
         and kept the Movement afloat as many adults were called up for the war,
          with the youth entirely leading the patrols.'
      ],
     ] ,
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1916:</span> Для хлопчиків віком
                до 11 років було започатковано вікову секцію «Кабскаутинг», який
                підтримувався публікацією “Посібника для вовченяти” та
                використанням “Книги джунглів” Редьярда Кіплінга як основи для
                Скаутингу.',
        'en' => '<span class="regular-block-text-bold">1916:</span>  Cub Scouts was started
         for boys under the age of 11, supported by the publication of
         the “Wolf Cub’s Handbook” and using Rudyard Kipling’s “Jungle Book” as a framework.'
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">1918:</span> Створено вікову
                секцію “Роверство” для старших хлопців та молоді.',
        'en' => '<span class="regular-block-text-bold">1918:</span> Rover Scouts
         was formed for older boys and young adults.'
      ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo3.jpg",
    "dates" => "1919 – 1922",
    "title" => [
      'ukr' => "Всесвітні події та керівництво Скаутингом",
      'en' => 'Scouting’s World Events and Governance '
    ],
    "texts" => [
    
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1920:</span> Перша Всесвітня
                Скаутська Конференція (тоді відома як Міжнародна Скаутська
                Конференція) відбулася під час першого Всесвітнього Скаутського
                Джамборі в Лондоні, Велика Британія, за участю 33 Національних
                Скаутських Організацій.',
        'en' => '<span class="regular-block-text-bold">1920:</span>  The first World Scout Conference
         (then known as the International Scout Conference) 
         took place during the first World Scout Jamboree in London, United Kingdom,
          with 33 National Scout Organizations in attendance.'
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">1920:</span> У Лондоні, Велика
                Британія, було створено Всесвітнє Скаутське Бюро (тоді відоме як
                Міжнародне Бюро Бойскаутів).',
        'en' => '<span class="regular-block-text-bold">1920:</span>
         The World Scout Bureau (then known as the Boy Scouts International Bureau)
          was established in London, United Kingdom.'
      ],],
      [
        "text" => [
          'ukr' => '<span class="regular-block-text-bold">1922:</span> У Парижі, Франція,
                відбулася друга Всесвітня Скаутська Конференція, на якій була
                представлена 31 Національна Скаутська Організація. Глобальне
                членство становило трохи більше 1 мільйона Скаутів.',
          'en' => '<span class="regular-block-text-bold">1922:</span> 
          The 2nd World Scout Conference was held Paris, France, with 31
           National Scout Organizations represented. Global membership
            stood at just over 1 million Scouts.'
        ],
       ],
        ["text" => [
          'ukr' => '<span class="regular-block-text-bold">1922:</span> Обрано перший
                Всесвітній Скаутський Комітет (тоді Міжнародний Комітет
                Бойскаутів).',
          'en' => '<span class="regular-block-text-bold">1922:</span>
           The first World Scout Committee (then Boy Scouts  International Committee) was elected.'
        ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo4.jpg",
    "dates" => "1914 – 1945",
    "title" => [
      'ukr' => "Світові війни",
      'en' => 'The World Wars'
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => "  Між двома світовими війнами Скаутинг продовжував процвітати, за
                винятком тоталітарних регіонів, де Скаутська діяльність була
                заборонена. В окупованих країнах з тоталітарними режимами
                Скаутинг продовжував існувати таємно, а Скаути відігравали
                важливу роль у русі опору. Скаути підтримували свої країни під
                час світових воєн, годуючи голодних та допомагаючи пораненим.
                Подекуди морські Скаути виконували функції берегової охорони.",
        'en' => "Between the two world wars, Scouting continued to flourish,
         except in totalitarian regions where Scouting activities were banned.
          In occupied countries and in those with totalitarian regimes, 
          Scouting continued in secret with Scouts playing important roles
           in the resistance and underground movements. Scouts supported their
            countries through the world wars by feeding the hungry and helping 
            the injured. In some places, Seas Scouts acted as coast guards."
      ],
     ] ,
     
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo5.jpg",
    "dates" => "1945 – 1980",
    "title" => [
      'ukr' => "Еволюція Скаутингу",
      'en' => 'The Evolution of Scouting'
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => '',
        'en' => ''
      ],
     ] ,
     [
      "text" => [
        'ukr' => '',
        'en' => ''
      ],
     ],
      ["text" => [
        'ukr' => '',
        'en' => ''
      ],],
      
    ]

  ],
  [
    "src" => "",
    "dates" => "",
    "title" => [
      'ukr' => "",
      'en' => ''
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => "",
        'en' => ""
      ],
     ] ,
     [
      "text" => [
        'ukr' => '',
        'en' => ''
      ],
     ],
      ["text" => [
        'ukr' => '',
        'en' => ''
      ],],
      
    ]

  ],
  [
    "src" => "",
    "dates" => "",
    "title" => [
      'ukr' => "",
      'en' => ''
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => "",
        'en' => ""
      ],
     ] ,
     [
      "text" => [
        'ukr' => '',
        'en' => ''
      ],
     ],
      ["text" => [
        'ukr' => '',
        'en' => ''
      ],],
      
    ]

  ],
  [
    "src" => "",
    "dates" => "",
    "title" => [
      'ukr' => "",
      'en' => ''
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => "",
        'en' => ""
      ],
     ] ,
     [
      "text" => [
        'ukr' => '',
        'en' => ''
      ],
     ],
      ["text" => [
        'ukr' => '',
        'en' => ''
      ],],
      
    ]

  ],
  [
    "src" => "",
    "dates" => "",
    "title" => [
      'ukr' => "",
      'en' => ''
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => "",
        'en' => ""
      ],
     ] ,
     [
      "text" => [
        'ukr' => '',
        'en' => ''
      ],
     ],
      ["text" => [
        'ukr' => '',
        'en' => ''
      ],],
      
    ]

  ],
];
