<?php
return [

  [
    "src" => "./images/scouting-history/photo1.jpg",
    "dates" => [
      'ukr' => "1907 – 1908",
      'en' => "1907 – 1908"
    ],
    "title" => [
      'ukr' => "Ранні роки",
      'en' => 'Early Beginnings'
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => "Скаутинг розпочався як програма для хлопчиків віком
                    від 11 до 18 років.",
        'en' => "Scouting began as a programme for boys aged 11 to 18."
      ],
     ] ,
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1907:</span> Перший
                    експериментальний табір, організований Робертом Бейден-Поуеллом
                    з 20 хлопчиками на острові Браунсі, Велика Британія, мав великий
                    успіх.',
        'en' => '<span class="regular-block-text-bold">1907:</span> The first experimental camp organized by
         Robert Baden-Powell with 20 boys at Brownsea Island,
          United Kingdom was a great success.'
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">1908:</span> Бейден-Поеулл
                    опублікував книгу “Скаутинг для хлопчиків”, яка одразу ж стала
                    відомою і з того часу була продана накладом понад 100 мільйонів
                    примірників.',
        'en' => '<span class="regular-block-text-bold">1908:</span> Baden-Powell published
         “Scouting for Boys”, which was an immediate hit and has since sold over 100 million copies.'
      ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo2.jpg",
   "dates" => [
      'ukr' => "1909 – 1918",
      'en' => "1909 – 1918"
    ],
    "title" => [
      'ukr' => "Розширення Скаутського Руху",
      'en' => 'Expansion of the Scout Movement'
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1909:</span> “Скаутинг для
                хлопчиків” був перекладений п’ятьма мовами. Це породило Рух,
                який швидко взяв назву “Бойскаути”.',
        'en' => '<span class="regular-block-text-bold">1909:</span> "Scouting for Boys" 
        was translated into five languages. It produced a Movement that quickly 
        adopted the name “The Boy Scouts”.'
      ],
     ] ,
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1909:</span> Скаутський зліт у
                Лондоні зібрав понад 11 000 Скаутів.',
        'en' => '<span class="regular-block-text-bold">1909:</span> A Scout rally in London attracted more than 11,000 Scouts.'
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">1910:</span> Бейден-Поеулл
                заснував Організацію для дівчат-Гайдів під керівництвом своєї
                сестри Агнес.',
        'en' => '<span class="regular-block-text-bold">1910:</span> Baden-Powell 
        started the Girl Guides under the leadership of his sister, Agnes.'
      ],
    ],
    [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1914:</span> Система Патрулів
                була створена для забезпечення стабільности Скаутингу під час
                Першої світової війни, оскільки Патрульні Лідери були
                добровольцями, які замінили дорослих лідерів.',
        'en' => '<span class="regular-block-text-bold">1914: </span> After the outbreak
         of World War I, the Patrol System proved highly effective
         and kept the Movement afloat as many adults were called up for the war,
          with the youth entirely leading the patrols.'
      ],
     ] ,
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1916:</span> Для хлопчиків віком
                до 11 років було започатковано вікову секцію «Кабскаутинг», який
                підтримувався публікацією “Посібника для вовченяти” та
                використанням “Книги джунглів” Редьярда Кіплінга як основи для
                Скаутингу.',
        'en' => '<span class="regular-block-text-bold">1916:</span>  Cub Scouts was started
         for boys under the age of 11, supported by the publication of
         the “Wolf Cub’s Handbook” and using Rudyard Kipling’s “Jungle Book” as a framework.'
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">1918:</span> Створено вікову
                секцію “Роверство” для старших хлопців та молоді.',
        'en' => '<span class="regular-block-text-bold">1918:</span> Rover Scouts
         was formed for older boys and young adults.'
      ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo3.jpg",
    "dates" => [
      'ukr' => "1919 – 1922",
      'en' => "1919 – 1922"
    ],
    "title" => [
      'ukr' => "Всесвітні події та керівництво Скаутингом",
      'en' => 'Scouting’s World Events and Governance '
    ],
    "texts" => [
    
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1920:</span> Перша Всесвітня
                Скаутська Конференція (тоді відома як Міжнародна Скаутська
                Конференція) відбулася під час першого Всесвітнього Скаутського
                Джамборі в Лондоні, Велика Британія, за участю 33 Національних
                Скаутських Організацій.',
        'en' => '<span class="regular-block-text-bold">1920:</span>  The first World Scout Conference
         (then known as the International Scout Conference) 
         took place during the first World Scout Jamboree in London, United Kingdom,
          with 33 National Scout Organizations in attendance.'
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">1920:</span> У Лондоні, Велика
                Британія, було створено Всесвітнє Скаутське Бюро (тоді відоме як
                Міжнародне Бюро Бойскаутів).',
        'en' => '<span class="regular-block-text-bold">1920:</span>
         The World Scout Bureau (then known as the Boy Scouts International Bureau)
          was established in London, United Kingdom.'
      ],],
      [
        "text" => [
          'ukr' => '<span class="regular-block-text-bold">1922:</span> У Парижі, Франція,
                відбулася друга Всесвітня Скаутська Конференція, на якій була
                представлена 31 Національна Скаутська Організація. Глобальне
                членство становило трохи більше 1 мільйона Скаутів.',
          'en' => '<span class="regular-block-text-bold">1922:</span> 
          The 2nd World Scout Conference was held Paris, France, with 31
           National Scout Organizations represented. Global membership
            stood at just over 1 million Scouts.'
        ],
       ],
        ["text" => [
          'ukr' => '<span class="regular-block-text-bold">1922:</span> Обрано перший
                Всесвітній Скаутський Комітет (тоді Міжнародний Комітет
                Бойскаутів).',
          'en' => '<span class="regular-block-text-bold">1922:</span>
           The first World Scout Committee (then Boy Scouts  International Committee) was elected.'
        ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo4.jpg",
    "dates" => [
      'ukr' => "1914– 1945",
      'en' => "1914– 1945"
    ],
    "title" => [
      'ukr' => "Світові війни",
      'en' => 'The World Wars'
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => "  Між двома світовими війнами Скаутинг продовжував процвітати, за
                винятком тоталітарних регіонів, де Скаутська діяльність була
                заборонена. В окупованих країнах з тоталітарними режимами
                Скаутинг продовжував існувати таємно, а Скаути відігравали
                важливу роль у русі опору. Скаути підтримували свої країни під
                час світових воєн, годуючи голодних та допомагаючи пораненим.
                Подекуди морські Скаути виконували функції берегової охорони.",
        'en' => "Between the two world wars, Scouting continued to flourish,
         except in totalitarian regions where Scouting activities were banned.
          In occupied countries and in those with totalitarian regimes, 
          Scouting continued in secret with Scouts playing important roles
           in the resistance and underground movements. Scouts supported their
            countries through the world wars by feeding the hungry and helping 
            the injured. In some places, Seas Scouts acted as coast guards."
      ],
     ] ,
     
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo5.jpg",
    "dates" => [
      'ukr' => "1945 – 1980",
      'en' => "1945 – 1980"
    ],
    "title" => [
      'ukr' => "Еволюція Скаутингу",
      'en' => 'The Evolution of Scouting'
    ],
    "texts" => [
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1947:</span> Всесвітня
                Організація Скаутського Руху отримала загальний консультативний
                статус при Економічній і Соціальній Раді Організації Об’єднаних
                Націй (ЮНЕСКО).',
        'en' => '<span class="regular-block-text-bold">1947:</span>
         World Organization of the Scout Movement was granted General
          Consultative Status to the United Nations Economic and Social Council (UNESCO).'
      ],
     ] ,
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">1960-1980:</span> Багато країн
                здобули незалежність, в результаті чого Національні Скаутські
                Організації приєдналися або знову стали членами Всесвітньої
                Організації Скаутського Руху.',
        'en' => '<span class="regular-block-text-bold">1960-1980:</span>
         Many countries gained their independence, resulting in National Scout Organizations 
         joining or rejoining as members of World Organization of the Scout Movement. '
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">1980-2007:</span> Скаутинг
                відродився в усіх країнах, де він існував до Другої світової
                війни, а також у нових незалежних країнах Співдружності
                Незалежних Держав після закінчення холодної війни. Скаутинг у
                країнах, що розвиваються, поступово перетворився на молодіжну
                програму, яка була розроблена місцевими Скаутськими лідерами для
                кращого задоволення потреб своїх громад. Скаути стали більш
                залученими до вирішення соціальних, економічних та екологічних
                питань у своїх громадах та країнах.',
        'en' => '<span class="regular-block-text-bold">1980-2007:</span>
         Scouting re-emerged in every country where it had existed before
          World War II and started across newly independent countries
           in the Commonwealth of Independent States following the Cold War. 
           Scouting in developing countries gradually evolved into a Youth Programme,
            which was designed by local Scout leaders to better meet the needs
             of their communities. Scouts became more involved with social, economic,
              and environmental issues in their communities and countries.'
      ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo6.jpg",
    "dates" => [
      'ukr' => "2007",
      'en' => "2007"
    ],
    "title" => [
      'ukr' => "Століття Скаутингу",
      'en' => 'A Century of Scouting'
    ],
    "texts" => [
    
     [
      "text" => [
        'ukr' => ' Скаутський рух відсвяткував своє
                <span class="regular-block-text-bold">100-річчя,</span> повернувшись
                до свого коріння у Великій Британії на 21-й Всесвітнє Скаутське
                Джамборі.',
        'en' => 'The Scout Movement celebrated its <span class="regular-block-text-bold">100th anniversary</span> 
        by returning to its roots in the United Kingdom for the 21st World Scout Jamboree.'
      ],
     ],
      ["text" => [
        'ukr' => '1 серпня мільйони Скаутів з усього світу відсвяткували створення
                Скаутського Руху та його зростання від скромних початків до
                глобального Руху з мільйонами членів майже в кожній країні
                світу.',
        'en' => 'On 1 August, millions of Scouts from around the world celebrated 
        the Scout Movement and its growth from humble beginnings to becoming 
        a global Movement with millions of members in nearly every country around the world.'
      ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo7.jpg",
    "dates" => [
      'ukr' => "2010 – 2020",
      'en' => "2010 – 2020"
    ],
    "title" => [
      'ukr' => " Сприяння миру і сталости",
      'en' => 'Promoting Peace and Sustainability'
    ],
    "texts" => [
      [
        "text" => [
          'ukr' => 'Скаутинг продовжував розширювати своє членство, охоплюючи навіть
                віддалені острови в Тихому океані та Карибському басейні,
                одночасно впроваджуючи інновації та адаптуючи свої освітні
                пропозиції відповідно до сучасних потреб та прагнень молоді.',
          'en' => 'Scouting continued to expand its membership - reaching even 
          remote islands in the Pacific and Caribbean - while innovating and adapting
           its educational offerings to reflect the current needs and aspirations of young people.'
        ],
       ],
        ["text" => [
          'ukr' => ' <span class="regular-block-text-bold">2011:</span> Ініціатива “Посланці
                миру” була створена для сприяння розбудови миру та підтримки
                впливу Скаутингу на місцеві громади.',
          'en' => '<span class="regular-block-text-bold">2011:</span>
           The Messengers of Peace initiative was created to promote peace
            building and support Scouting’s impact on local communities.'
        ],],
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">2018:</span> Започатковано
                ініціативу “Скаути за Цілі Сталого Розвитку (ЦСР)” з метою
                залучення Скаутського Руху до найбільшого у світі
                скоординованого внеску молоді у досягнення ЦСР.',
        'en' => '<span class="regular-block-text-bold">2018:</span>
         Scouts for SDGs was launched with the aim of engaging the Scout Movement
          in making the world’s largest coordinated youth contribution to the SDGs.'
      ],
     ],
      ["text" => [
        'ukr' => '<span class="regular-block-text-bold">2020:</span> Створено глобальну
                молодіжну спільноту “Earth Tribe”, що об’єднує молодь для
                природоохоронної діяльности та надання можливости молодим людям
                боротися з наслідками зміни клімату.',
        'en' => '<span class="regular-block-text-bold">2020:</span>
         The Earth Tribe was launched as a global youth community for
          environmental action and to enable young people to tackle the impacts of climate change.'
      ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo8.jpg",
    
    "dates" => [
      'ukr' => "2020 – 2022",
      'en' => "2020 – 2022"
    ],
    "title" => [
      'ukr' => "Всесвітня пандемія",
      'en' => 'Global Pandemic'
    ],
    "texts" => [
     
     [
      "text" => [
        'ukr' => '<span class="regular-block-text-bold">2020-2022:</span> Скаути по
                всьому світу продемонстрували стійкість Руху, вживаючи заходів
                для підтримки своїх громад та адаптуючись до глобальних обмежень
                через віртуальні програми. ',
        'en' => '<span class="regular-block-text-bold">2020-2022:</span> 
        Scouts around the world showed the Movement`s resilience by taking action
         to support their communities and adapting to global restrictions through
          virtual and at-home programmes.'
      ],
     ],
      ["text" => [
        'ukr' => ' <span class="regular-block-text-bold">2022:</span> Ініціатива
                “Глобальна мобілізація молоді” (Global Youth Mobilisation) була
                започаткована з метою підтримки розвитку молоді у
                постпандемічному світі. Це партнерство з Великою шісткою
                молодіжних організацій, до якої входять Всесвітня Організація
                Скаутського Руху (WOSM), Всесвітня Асоціація дівчат-Гайдів та
                дівчат-Скаутів (WAGGGS), Всесвітній альянс християнських
                асоціацій молодих чоловіків (YMCA), Всесвітня християнська
                асоціація молодих жінок (YWCA), Міжнародна федерація товариств
                Червоного Хреста і Червоного Півмісяця, (IFRC) а також
                Міжнародна премія герцога Единбурзького (DofE).',
        'en' => '<span class="regular-block-text-bold">2022:</span>
         The Global Youth Mobilization was launched in an effort
          to support the development of young people in a post-pandemic world. 
          It is as a partnership with the Big 6 Youth Organisations, which is
           comprised of the World Organization of the Scout Movement,
            World Association of Girl Guides and Girl Scouts, World Alliance of 
            Young Men’s Christian Association, World Young Women’s Christian Association, 
            International Federation of Red Cross and Red Crescent Societies, 
            and The Duke of Edinburgh’s International Award.'
      ],],
      
    ]

  ],
  [
    "src" => "./images/scouting-history/photo9.jpg",
    "dates" => [
      'ukr' => "2022- Сьогодення",
      'en' => '2022- The present'
    ],
     	

    "title" => [
      'ukr' => "Еволюція Скаутингу",
      'en' => 'The evolution of Scouting'
    ],
    "texts" => [
    
     [
      "text" => [
        'ukr' => 'Після пандемії COVID-19 Всесвітня Організація Скаутського Руху
                продовжила розвивати нову стратегію, щоб краще відповідати на
                виклики сучасного світу та потреби молоді. Одним з головних
                напрямів розвитку є залучення більшої кількості молоді до
                Скаутингу та збільшення різноманітності членства, включаючи
                більш ефективну роботу з молоддю з малозабезпечених та вразливих
                груп.',
        'en' => 'In the wake of the COVID-19 pandemic, the World Organization
         of the Scout Movement has continued to develop a new strategy to better
          respond to the challenges of the modern world and the needs of young people.
           One of the main areas of development is to attract more young people to Scouting and increase the diversity of membership, including more effective work with young people from low-income and vulnerable groups.'
      ],
     ],
      ["text" => [
        'ukr' => 'Крім того, Скаути активно співпрацюють з урядами та іншими
                громадськими організаціями для реалізації Цілей сталого розвитку
                ООН та підтримки збереження навколишнього середовища.',
        'en' => 'n addition, the Scouts actively cooperate with governments 
        and other NGOs to implement the UN Sustainable Development Goals and support environmental protection.'
      ],],
      
    ]

  ],
];
