<?php
return [

  [
    "src" => "/images/our-history/photo1.png",

    "title" => [
      'ua' => "Початок 20-го століття",
      'en' => 'The Early 20th Century'
    ],
    "texts" => [
      [
        "text" => [
          'ua' => "Скаутинг на території України має багату історію, що сягає
                      початку 20-го століття. Оскільки в цей час Скаутський рух
                      швидко поширювався по всій Європі, в Україні також було
                      створено кілька Скаутських організацій, які мали на меті
                      виховувати та навчати молодь відповідно до принципів
                      Cкаутингу.",
          'en' => "Scouting in Ukraine has a rich history that dates back to the early 20th century. 
As the Scouting movement spread rapidly across Europe, several 
Scout organizations were established in Ukraine, aiming to educate and 
train young people according to the principles of Scouting.
 "
        ],
      ],
      [
        "text" => [
          'ua' => 'Однак за радянських часів Скаутська діяльність була
                      заборонена, і багато Скаутських організацій були змушені
                      розпуститися або діяти підпільно. Багато українських
                      Cкаутів знайшли притулок в инших країнах, де вони змогли
                      зберегти свої традиції та зберегти сильне почуття
                      ідентичности та мети. Попри всі виклики та перешкоди,
                      Скаутський дух залишився живим, і українські Скаутські
                      групи продовжували існувати і процвітати в еміграції.',
          'en' => 'However USSR was banning Scouting activities, and many 
Scout organizations were forced to disband or operate silently. 
Many Ukrainian Scouts sought refuge in other countries, where they were 
able to preserve their traditions and maintain a strong sense of identity. 
Despite all challenges and obstacles, the Scouting spirit 
remained, and Ukrainian Scout groups continued to exist and thrive in exile.'
        ],
      ],


    ]

  ],
  [
    "src" => "/images/our-history/photo2.jpg",

    "title" => [
      'ua' => "Незалежність України",
      'en' => 'Ukraine’s Independence'
    ],
    "texts" => [
      [
        "text" => [
          'ua' => "Після здобуття Україною незалежности в 1991 році та
                      подальшого розпаду Радянського Союзу, Cкаутський Рух
                      поступово почав відроджуватися в країні.",
          'en' => "After Ukraine gained independence in 1991 and the following
fall of the Soviet Union, the Scouting movement gradually 
began to revive."
        ],
      ],
      [
        "text" => [
          'ua' => 'Цей процес був тривалим, і лише у 2000-их роках
                      розпочалася паперова робота по стовреню Організації
                      Скаутського Руху в Україні. Таким чином, у 2007 році була
                      офіційно заснована Національна Організація Скаутів України
                      (НОСУ), що стало новою сторінкою в історії Скаутингу в
                      Україні.',
          'en' => 'This process was lengthy, and it wasn’t 
until the 2000s that the groundwork began for establishing 
a national Scouting organization in Ukraine. Thus, in 2007, 
the National Organization of the Scouts of Ukraine was officially 
founded, marking a new chapter in the history of Scouting in Ukraine.'
        ],
      ],
      [
        "text" => [
          'ua' => 'Це відродження ознаменувало тріумфальне повернення
                      Cкаутського Руху і стало свідченням стійкости та рішучости
                      українських Cкаутів як вдома, так і за кордоном.',
          'en' => 'This revival signified the triumphant return of the Scouting 
movement and served as a testament to the resilience and 
determination of Ukrainian Scouts both at home and abroad.'
        ],
      ],


    ]

  ],
  [
    "src" => "/images/our-history/photo3.jpg",

    "title" => [
      'ua' => "Міжнародне визнання",
      'en' => 'International Recognition'
    ],
    "texts" => [
      
      [
        "text" => [
          'ua' => 'За короткий проміжок часу НОСУ здобула міжнародне
                      визнання, ставши повноправним членом Всесвітньої
                      організації Скаутського Руху (ВОСР) під час 38-ї
                      Всесвітньої Скаутської Конференції в Кореї у 2008 році. Ця
                      подія стала важливою віхою в історії НОСУ, закріпивши її
                      місце у світовій Скаутській спільноті. З моменту свого
                      заснування НОСУ значно зросла і зараз налічує понад 2 000
                      відданих членів, які беруть активну участь у різноманітних
                      програмах, спрямованих на особистісний розвиток,
                      громадську діяльність та охорону навколишнього середовища.
                      Протягом усієї своєї історії НОСУ відстоює цінности
                      Скаутингу, серед них лідерство, командну роботу та повагу
                      до инших людей і світу природи.',
          'en' => "In a short period, NOSU achieved international recognition, becoming 
a member of the World Organization of the Scout Movement 
during the 38th World Scout Conference in Korea in 2008. 
This event was a significant milestone in NOSU's history, solidifying 
its place in the global Scouting community. Since its founding, 
NOSU has grown substantially and now includes over 2,000 
dedicated members actively involved in various programs focused 
on personal development, community service, and environmental 
conservation. Throughout its history, NOSU has upheld Scouting 
values, including leadership, teamwork, and respect for others 
and the nature."
        ],
      ],


    ]

  ],
  [
    "src" => "/images/our-history/photo4.jpg",

    "title" => [
      'ua' => "Глобальна мережа НОСУ сьогодні",
      'en' => 'The Global Network of NOSU Today'
    ],
    "texts" => [
    
      [
        "text" => [
          'ua' => " Глобальна мережа НОСУ охоплює 173 країни-партнери, що
                      зміцнює міжнародну дружбу та співпрацю, які, в свою чергу,
                      сприяють культурному обміну та взаєморозумінню. Ця мережа
                      партнерств дозволила НОСУ запропонувати широкий спектр
                      закордонних програм та спільних заходів, надаючи Скаутам
                      унікальний досвід, що розширює їхній кругозір та розвиває
                      їхню глобальну свідомість. Окрім інтернаціональних
                      партнерств, НОСУ має значний вплив в Україні,
                      організовуючи та беручи участь у численних громадських
                      проєктах та ініціативах. Ці зусилля не лише принесли
                      користь місцевим громадам, але й розвили потужне почуття
                      громадянського обов’язку та соціальної відповідальности у
                      членів Організації.",
          'en' => 'NOSU’s global network spans 174 partner countries, 
boosting international friendships and collaborations. This partnership 
network has gave NOSU the chance to offer a broad range 
of international programs and joint activities, providing Scouts with 
unique experiences that broaden their horizons and develop their 
world awareness. In addition to its international partnerships, 
NOSU has a significant impact within Ukraine by organizing and 
participating in numerous community projects and initiatives. 
These efforts have not only benefited local communities but have 
also instilled a strong sense of civic duty and social responsibility 
in the Organization’s members.'
        ],
      ],


    ]

  ],
  [
    "src" => "/images/our-history/photo5.jpg",

    "title" => [
      'ua' => "Можливості НОСУ",
      'en' => 'Opportunities with NOSU'
    ],
    "texts" => [
      
      [
        "text" => [
          'ua' => 'НОСУ пропонує різноманітні та цікаві освітні можливости,
                      які відповідають інтересам та потребам своїх членів. На
                      даний момент було проведено понад 1 320 заходів, що
                      сприяють розвитку нашого юного покоління. Ці заходи
                      охоплюють багатий вибір тем – від збереження довкілля та
                      сталого життя до розвитку лідерства та готовности
                      реагувати на надзвичайні ситуації. Включаючись у ці
                      освітні заходи, Скаути НОСУ здобувають цінні навички та
                      знання, що допомагають їм стати всебічно розвиненими
                      особистостями та активними членами суспільства. Національна
                      Організація Скаутів України продовжує зростати та
                      розвиватися, залишаючись відданою своїм основоположним
                      принципам та цінностям. Маючи багату історію діяльности на
                      місцевому та міжнародному рівнях, НОСУ прагне виховувати
                      наступне покоління лідерів, новаторів та громадян світу.',
          'en' => 'NOSU offers diverse and engaging educational opportunities designed
for the interests and needs of its members. Over 1,320 events 
have been held to support the development of our 
younger generation for today. These events cover a wide range 
of topics—from environmental conservation and sustainable living 
to leadership development and emergency prepareness. 
By participating in these educational activities, scouts 
gain valuable skills and knowledge that help them become 
well-rounded individuals and active members of society. 
The National Organization of the Scouts of Ukraine continues 
to grow and evolve, remaining committed to its core 
principles and values. Having rich history of activity at both 
local and international levels, NOSU strives to raise
the next generation of leaders, innovators, and citizens of the world.'
        ],
      ],


    ]

  ],
];
