<?php
return [

  "main-title" => [
    'ukr' => "Наша історія",
    'en' => "Our History",
  ],
  
  "additional-text" => [
    'ukr' => "Хочеш дізнатися більше не тільки про цей Рух в Україні, а про
                історію Скаутингу у світі загалом?",
    'en' => "Would you like to learn more not only about Scouts of Ukraine, 
but also about the history of Scouting worldwide?",
  ],
  
  "additional-link" => [
    'ukr' => "Переходь за посиланням!",
    'en' => "Click the link to explore!",
  ],
 
  
];
