<?php
return [
  [
    "law-text" => [
      'ukr' => " Розвиток Скаутських груп у деокупованих територіях України та в малих містах.",
      'en' => "Development of Scout groups in de-occupied areas of Ukraine and small towns."
    ]
  ],
  [
    "law-text" => [
      'ukr' => " Підготовку дорослих лідерів для їхньої ефективної роботи з дітьми у Скаутах України.",
      'en' => "Training adult leaders to work effectively with children within Scouts of Ukraine."
    ]
  ],
  [
    "law-text" => [
      'ukr' => "Підтримку дітей, які змушені були змінити місце проживання через війну.",
      'en' => "Supporting children who were forced to relocate due to the war."
    ]
  ],
  [
    "law-text" => [
      'ukr' => " Організацію адаптаційних Скаутських таборів для дітей, постраждалих від війни.",
      'en' => "Organizing adaptation Scout camps for children affected by the war."
    ]
  ],
];














