<?php
return [

  "main-title" => [
    'ukr' => "Допомога організації",
    'en' => "Support Our Organization",
  ],
  "first-additional-text" => [
    'ukr' => "Ми робимо світ кращим! Приєднуйтесь і підтримайте нас!",
    'en' => "We’re Making the World a Better Place! Join Us and Help Make a Difference!",
  ],
  "second-additional-text" => [
    'ukr' => "Кожного дня ми - Скаути України - робимо нашу країну
                      кращою! Ми створюємо та реалізовуємо соціальні та
                      гуманітарні проєкти, навчаємо та виховуємо дітей,
                      організовуємо табори, а ще мріємо про найкрутіший
                      Скаутський центр - дім для всіх Скаутів в Україні.",
    'en' => "Every day, we – the Scouts of Ukraine – are working 
    to improve our country! We create and implement social and humanitarian 
    projects, educate and mentor children, organize camps, and dream of building 
    the ultimate Scout Center – a home for all Scouts in Ukraine.",
  ],
  "third-additional-text" => [
    'ukr' => "Для того, щоб дізнатися більше про проєкти, які ми
                      реалізуємо завдяки вашій підтримці, переходьте за цим
                      посиланням (стр наші проєкти). Тут ви зможете побачити, як
                      саме ваш внесок допомагає нам змінювати життя українців на
                      краще.",
    'en' => "To learn more about the projects we’re bringing to life with your support,
     follow this link (see Our Projects page). Here, you’ll be able to see how
      your contribution helps us make a positive difference in the lives of Ukrainians.",
  ],
  
  "donation-text" => [
    'ukr' => " Ваші пожертви допомагають підтримати важливі гуманітарні
                      та соціальні проєкти Національної Організації Скаутів
                      України. Наразі ми зосереджені на зборі 500.000 гривень
                      протягом 2024 року, які спрямовуються на допомогу
                      українським родинам у час повномасштабної війни, а саме:",
    'en' => "Your Donations Help Support Essential Humanitarian and 
    Social Projects of the National Organization of Ukrainian Scouts. 
    Currently, we are focused on raising 500,000 UAH in 2024 to support 
    Ukrainian families during these challenging times of full-scale war.
     Your contributions will specifically go toward:",
  ],
  "donation-text-second" => [
    'ukr' => " У випадку, якщо зібрані кошти перевищать потреби
                    конкретного проєкту або якщо проєкт з якихось причин не
                    буде реалізований, залишкові кошти будуть перенаправлені
                    на інші актуальні проєкти Скаутів України. Таким чином, ми
                    гарантуємо, що ваша допомога завжди буде використана там,
                    де це найбільш потрібно.",
    'en' => "If the funds collected exceed the needs of a specific project
     or if a project is not implemented for any reason, remaining funds
      will be redirected to other relevant projects of the Scouts of Ukraine.
       This ensures that your support will always be used where it is most needed.",
  ],
  "donation-text-third" => [
    'ukr' => " Роблячи пожертву через платіжний сервіс LiqPay, ви
                    підтверджуєте свою згоду на використання коштів для
                    підтримки інших проєктів Скаутів України у цій категорії.
                    Також ви погоджуєтесь, що сума вашої пожертви не підлягає
                    поверненню.",
    'en' => "By donating through the LiqPay payment service, you confirm your
     agreement that your funds may be used to support other projects of the
      Scouts of Ukraine within this category. Additionally,
       you agree that your donation amount is non-refundable.",
  ],
  "donate-btn" => [
    'ukr' => "Задонатити",
    'en' => "Donate",
  ],
  "questions-title" => [
    'ukr' => "Часті запитання:",
    'en' => "Frequently Asked Questions:",
  ],
];
