<?php
return [
  [
    "questions" => [
      'ua' => "ЩЕ НЕ ПІЗНО ДОПОМАГАТИ?",
      'en' => "IS IT TOO LATE TO HELP?"
    ],
    "answer" => [
      'ua' => "Ніколи не пізно допомагати. Наші проєкти та ініціативи
                      постійно потребують підтримки, і кожен внесок має значення
                      для продовження нашої діяльності. Скаутинг продовжується
                      незважаючи на усі виклики, ми розвиваємося та зростаємо,
                      але в умовах війни, і наразі у нас постійно є Скаутські
                      групи, які мусять адаптуватися до нових умов, переїжджати
                      та ставити свою діяльність на паузу. Постійна підтримка
                      дітей та молодих людей, особливо у такий складний час, є
                      критично важливою для нас, аби продовжувати відкривати для
                      них світ Скаутингу. ",
      'en' => '"It’s never too late to help. Our projects and initiatives are always
      in need of support, and every contribution matters to sustain our efforts.
       Scouting continues to thrive despite challenges, evolving and growing even
        during wartime. Currently, many Scout groups must adapt to new conditions, 
        relocate, or temporarily pause their activities. Continuous support for children 
        and young people, especially in such difficult times, is essential to help us keep
         opening up the world of Scouting for them."'
    ]
  ],
  [
    "questions" => [
      'ua' => "ЯК МОЯ ПОЖЕРТВА МОЖЕ БУТИ ВИКОРИСТАНА?",
      'en' => "HOW CAN MY DONATION BE USED?"
    ],
    "answer" => [
      'ua' => "Ваші кошти можуть будуть спрямовані на організаційний
                      розвиток, створення нових Скаутських осередків, навчання
                      дорослих лідерів, виготовлення Скаутської форми, участь
                      Скаутів в міжнародних заходах, літніх таборах у безпечних
                      місцях тощо. Окрім цього, ми продовжуємо проводити
                      гуманітарні та соціальні проєкти, такі як допомога
                      переселенцям та інші ініціативи, спрямовані на підтримку
                      громади.",
      'en' => '"Your funds may be allocated toward organizational development,
       creating new Scout centers, training adult leaders, producing Scout uniforms,
        enabling Scouts to attend international events, and organizing summer camps 
        in safe locations. In addition, we continue to implement humanitarian and 
        social projects, such as assisting displaced persons and other initiatives
         aimed at supporting communities."'
    ]
  ],
  [
    "questions" => [
      'ua' => "ЧИ МОЖНА ВАМ ДОПОМОГТИ ВІД ІМЕНІ КОМПАНІЇ?",
      'en' => "CAN I SUPPORT YOU ON BEHALF OF A COMPANY?"
    ],
    "answer" => [
      'ua' => "Так, ми завжди відкриті до співпраці та вдячні за будь-яку
                      підтримку від компаній, які поділяють наші цінності та
                      бажають долучитися до нашої місії. Партнерство із Скаутами
                      України дозволяє створити якісне середовище для розвитку
                      молодих людей, особливо у такий важкий час. Якщо ваша
                      компанія бажає стати частиною нашої спільноти та допомогти
                      у реалізації важливих ініціатив, будь ласка, зв'яжіться з
                      нами.",
      'en' => '"Yes, we are always open to collaboration and grateful for any support
       from companies that share our values and wish to join our mission. 
       Partnering with Scouts of Ukraine creates a quality environment for
        youth development, especially in such challenging times.
         If your company would like to become part of our community and assist
          in realizing important initiatives, please reach out to us."'
    ]
  ],
  [
    "questions" => [
      'ua' => "ЧИ Є МОЖЛИВІСТЬ ВИЗНАЧИТИ КОНКРЕТНИЙ ПРОЄКТ ДЛЯ МОЄЇ
                      ПОЖЕРТВИ?",
      'en' => "CAN I DESIGNATE MY DONATION FOR A SPECIFIC PROJECT?"
    ],
    "answer" => [
      'ua' => "Так, ви маєте можливість вказати конкретний проєкт, на
                      який ви хотіли б спрямувати вашу пожертву. Після
                      здійснення пожертви ми залишимося на зв'язку з вами, щоб
                      інформувати про прогрес та вплив вашого внеску на обраний
                      проєкт.",
      'en' => '"Yes, you can specify a particular project for your donation.
       After your contribution, we will stay in touch to keep you informed
        about the progress and impact of your support on the chosen project."'
    ]
  ],
  [
    "questions" => [
      'ua' => " ЧИ МОЖУ Я ДОПОМОГТИ НЕ ТІЛЬКИ ФІНАНСОВО, АЛЕ Й
                      ВОЛОНТЕРСТВОМ?",
      'en' => "CAN I HELP NOT JUST FINANCIALLY BUT ALSO BY VOLUNTEERING?"
    ],
    "answer" => [
      'ua' => 'Так, ваша допомога може бути не лише фінансовою. Ми
                      вітаємо всіх, хто хоче долучитися до нашої діяльності як
                      волонтер. Відвідайте нашу сторінку про те, як приєднатися
                      до нас у ролі <a href="./join-us#scout-leader">Скаут-лідера</a>.',
      'en' => '"Yes, your help can extend beyond financial support.
       We welcome anyone interested in joining our efforts as a volunteer.
        Visit our page on how to join us as a <a href="./join-us#scout-leader">Scout Leader</a>"'
    ]
  ],
];