<?php
return [
  [
    "text" => [
      'ua' => " Скаутинг готує молодих людей бути активними громадянами
суспільства, надаючи їм навички та лідерські якости для
реагування на виклики, що з ними стикається наш світ.
Скаутська Молодіжна Програма є основою Скаутингу.",
      'en' => "Scouting prepares young people to be active citizens of society, giving them the skills and leadership qualities to respond to the world's challenges. The Scout Youth Program is the base of Scouting."
    ]
  ],
  [
    "text" => [
      'ua' => "Це відповідно організований, практичний навчальний процес для
дітей та підлітків, спрямований на гармонійний та всебічний
розвиток особистости задля досягнення свого найвищого
потенціалу.",
      'en' => "This is an appropriately organized, practical educational process for children and young people, aimed at harmonious and comprehensive personality development to achieve its highest potential."
    ]
  ],
  [
    "text" => [
      'ua' => "Молодіжна Програма розглядає шість вимірів розвитку молодої
людини – соціальний, фізичний, інтелектуальний, емоційний,
духовний та характер – через можливости, навчання та досвід.",
      'en' => "The Youth Programme addresses six dimensions of a young person's development – ​​social, physical, intellectual, emotional, spiritual, and character – through opportunities, learning and experience."
    ]
  ],
  [
    "text" => [
      'ua' => " “Наша програма не є директивною, а це означає, що ми визнаємо
розмаїття інтересів і досвіду наших молодих людей та
заохочуємо їх шукати цікаві та захопливі для них
завдання. Кожен може обрати заняття, що відповідає основним
напрямкам Програми, яке згодом стає частиною їхньої Скаутської
подорожі.",
      'en' => 'Our program is non-prescriptive, which means that we recognize the diversity of interests and experiences of our young people and encourage them to find interesting and exciting tasks. Everyone can choose an activity that corresponds to the main areas of the Programme, which later becomes part of their Scouting journey.'
    ]
  ],
  [
    "text" => [
      'ua' => "Ми приймаємо той факт, що кожен Скаут має власний спосіб
підходу до викликів, і заохочуємо кожного Скаута пройти свій
особливий шлях, щоб досягти вищих цілей.",
      'en' => "We accept the fact that each Scout has their own way of approaching challenges and encourage each Scout to follow their own special path to achieve higher goals."
    ]
  ]
];
