<?php
return [
  "meta-title" => [
    'ua' => "Наша місія",
    'en' => 'Our mission'
  ],
  "meta-description" => [
    'ua' => "Наша місія.",
    'en' => 'Our mission.'
  ],

  "page-title" => [
    'ua' => "Наша місія",
    'en' => "Our mission",
  ],
  "our-mission" => [
    'ua' => "Наша місія",
    'en' => "Our mission
",
  ],
  "our-program" => [
    'ua' => "Наша Програма",
    'en' => "Our Programme",
  ],
  "age-groups-title" => [
    'ua' => "Вікові групи",
    'en' => "Age groups",
  ],
  "organization-text" => [
    'ua' => "Вікові групи: Скаутинг поділяється на різні вікові групи або секції, кожна з яких пропонує відповідну до віку діяльність. Скаути НОСУ об’єднуються у 4 вікові секції:",
    'en' => "Age groups: Scouting is divided into different age groups or sections, each offering age-appropriate activities. NOSU Scouts are divided into 4 age sections:",
  ],
  "organization-text-second" => [
    'ua' => "  Такий розподіл гарантує, що дитина буде спілкуватися зі своїми
          однолітками та брати участь у належних заходах. Варто зазначити,
          що із однієї вікової секції в иншу кожен член організації
          переходить не індивідуально, а разом з друзями – своїм патрулем,
          тому межі кожної вікової групи не є сталими.",
    'en' => "This distribution ensures that the child will interact with their peers and participate in appropriate for this age activities. It is worth noting that from one age section to another, each member of the organization does not move individually, but together with their friends - in their patrol, therefore the boundaries of each age group are not set in stone.
",
  ],
  "main-title" => [
    'ua' => "Як це працює?",
    'en' => "How does it work?
",
  ],
  "additional-text-part" => [
    'ua' => "Хочеш дізнатися більше про історію Скаутів України?",
    'en' => "Do you want to learn more about the history of the Scouts of Ukraine?",
  ],
  "additional-text-link" => [
    'ua' => "Переходь за посиланням",
    'en' => "Follow the link",
  ],

];
