<?php
return [
  [
    "text" => [
      'ukr' => " Головна мета створення НОСУ – об’єднання зусиль молодих людей
                    задля побудови потужного Скаутського Руху в Україні, а також
                    представлення України на міжнародному рівні.",
      'en' => "The main goal of the creation of the Scouts of Ukraine is to unite the efforts of young people in order to build a powerful Scouting Movement in Ukraine, as well as to represent Ukraine at the international level."
    ]
  ],
  [
    "text" => [
      'ukr' => " “Наша Місія – це сприяння вихованню молоді України за системою
                    цінностей, заснованій на Скаутській Обіцянці та Скаутському
                    Законі.”",
      'en' => '"Our mission is to help educate the youth of Ukraine according to the system of values ​​based on the Scout Promise and the Scout Law."'
    ]
  ],
  [
    "text" => [
      'ukr' => "Через Скаутинг ми будуємо кращий світ, де люди
                    самореалізуються як особистості та відіграють конструктивну
                    роль у суспільстві. Ми хочемо і розвиваємо українське
                    суспільство, створюючи умови для всебічного формування
                    особистости на основі Скаутського методу. Ми докладаємо зусиль
                    щодня, щоб надати молоді України можливості зростати, робити
                    свій внесок в наближення миру, мандрувати, знайомитись зі
                    Скаутами інших країн тощо.",
      'en' => "Through Scouting, we build a better world where people realize themselves as individuals and play a constructive role in society. We want and develop Ukrainian society, creating conditions for comprehensive personality formation based on the Scout method. We make efforts every day to give the youth of Ukraine the opportunity to grow, contribute to peace, travel, meet Scouts of other countries, etc."
    ]
  ]
];
