<?php
return [
  [
    'src' => '/images/our-mission/child1.jpg',
    'alt' => [
      'ua' => '',
      'en' => ""
    ],
    'name' => [
      'ua' => 'Кабскаути',
      'en' => "Cub Scouts"
    ],
    'age' => [
      'ua' => '6-10 років',
      'en' => "6-10 years old "
    ],
  ],
  [
    'src' => '/images/our-mission/child2.jpg',
    'alt' => [
      'ua' => '',
      'en' => ""
    ],

    'name' => [
      'ua' => 'Скаути',
      'en' => "Scouts"
    ],
    'age' => [
      'ua' => '11-15 років',
      'en' => "11-15 years old "
    ],
  ],
  [
    'src' => '/images/our-mission/child3.jpg',
    'alt' => [
      'ua' => '',
      'en' => ""
    ],
    'name' => [
      'ua' => 'Венчури',
      'en' => "Venturers"
    ],
    'age' => [
      'ua' => '16-17 років',
      'en' => "16-17 years old"
    ],
  ],
  [
    'src' => '/images/our-mission/child4.jpg',
    'alt' => [
      'ua' => '',
      'en' => ""
    ],
    'name' => [
      'ua' => 'Ровери',
      'en' => "Rovers"
    ],
    'age' => [
      'ua' => '18-22 років',
      'en' => "18-22 years old"
    ],
  ],

];
 
 	
