<?php
return [
  [
    'src' => './images/our-mission/photo3.jpg',
    'alt' => [
      'ukr' => '',
      'en' => ""
    ],
    'text-title' => [
      'ukr' => 'Зустрічі',
      'en' => "Meetings"
    ],
    "text" => [
      'ukr' => " Скаути зазвичай зустрічаються у своїх патрулях чи групах
              раз на тиждень на зборах патруля/гурта. Для молодших дітей
              зустрічі проводять підготовлені дорослі волонтери, які
              називаються Скаутськими лідерами (Скаут лідерами). Діти
              старшого віку самоорганізовуються та проводять збори,
              Скаут лідер не включається повноцінно в цей процес, а лише
              спостерігає, направляє та допомагає за необхідности. Під
              час зборів Скаути вчаться новим навичкам, працюють над
              проєктами та планують майбутні події чи пригоди. Ці
              зустрічі не схожі на уроки в школі, адже дорослий лідер не
              є вчителем для дітей, він їхній друг та наставник.
              Скаутинг виховує лідерство та командну роботу, тому часто
              дорослий лідер виступає у ролі спостерігача за діяльностю
              Скаутів.",
      'en' => 'Scouts usually meet in their patrols or groups once a week for a patrol/group meeting. For younger children, meetings are conducted by trained adult volunteers called Scout Leaders. Older children self-organize and hold meetings, the Scout leader is not fully involved in this process, but only observes, guides, and helps if necessary. During meetings, Scouts learn new skills, work on projects, and plan future events or adventures. These meetings are not like lessons at school, because an adult leader is not a teacher for children, they are their friend and a mentor. Scouting teaches leadership and teamwork, so often an adult leader acts as an observer of the activities of the Scouts.'
    ],

  ],
  [
    'src' => './images/our-mission/photo4.JPG',
    'alt' => [
      'ukr' => '',
      'en' => ""
    ],
    'text-title' => [
      'ukr' => 'Діяльність',
      'en' => "Activity"
    ],
    "text" => [
      'ukr' => "Скаутинг передбачає поєднання активностей у приміщенні та на свіжому повітрі. Активності є масштабними і тривалими, як от: табори, походи тощо; так і короткі та вичерпні: наприклад, заняття з в’язання вузлів, надання першої домедичної допомоги та инше. Скаути працюють над суспільно корисними проєктами, що допомагають їм зрозуміти важливість віддачі та змін на краще у своїх громадах.",
      'en' => 'Scouting involves a combination of indoor and outdoor activities. Activities are large-scale and long-lasting, such as camps, hikes, etc.; as well as short and comprehensive: for example, classes on knots, providing first aid, and others. Scouts work on community service projects that help them understand the importance of giving back and making changes for the better in their communities.'
    ],

  ],
  [
    'src' => '../images/our-mission/photo5.png',
    'alt' => [
      'ukr' => '',
      'en' => ""
    ],
    'text-title' => [
      'ukr' => 'Відзнаки та нагороди',
      'en' => "Distinction and awards"
    ],
    "text" => [
      'ukr' => "Здобуваючи різні вміння та отримуючи різний досвід через
              участь у заходах та проєктах, Скаути можуть здобувати
              відзнаки та нагороди, які символізують їхні здобутки. Ця
              система заохочує особистісний ріст та мотивує Скаутів
              кидати виклик самим собі і пробувати щось нове.",
      'en' => ' By learning different skills and gaining different experiences through participation in activities and projects, Scouts can earn badges and awards that symbolise their achievements. This system encourages personal growth and motivates Scouts to challenge themselves and try new things.'
    ],

  ],
  [
    'src' => './images/our-mission/photo6.jpg',
    'alt' => [
      'ukr' => '',
      'en' => ""
    ],
    'text-title' => [
      'ukr' => 'Цінності та Метод',
      'en' => "Values ​​and Method"
    ],
    "text" => [
      'ukr' => '  Скаутинг побудований навколо набору основних цінностей,
              які підкріплюються Скаутською Обіцянкою та Законом.
              Детальніше про них в розділі
              <a class="regular-block-text additional-text-link" href="./scout-method">Скаутський Метод</a>',
      'en' => 'Scouting is built around a set of core values ​​that are underpinned by the Scout Promise and Law. More about them you can read in the <a class="regular-block-text additional-text-link" href="./scout-method">Scout Method</a> section'
    ],

  ],
  [
    'src' => './images/our-mission/photo7.jpg',
    'alt' => [
      'ukr' => '',
      'en' => ""
    ],
    'text-title' => [
      'ukr' => 'Підтримка та безпека',
      'en' => "Support and safety"
    ],
    "text" => [
      'ukr' => " Скаутські організації всього світу надають пріоритет
              безпеці та добробуту своїх членів, і НОСУ не є
              винятком. Наші Скаутські лідери проходять спеціальне
              навчання “Захист від шкоди”, розроблене та запатентоване
              ВОСР, аби гарантувати безпечне та сприятливе середовище
              для всіх учасників Скаутського Руху у будь-якій
              діяльності. У Скаутингу кожен член Організації отримує
              можливість здобути цінні життєві навички, знайти друзів на
              все життя, стати рушієм змін на локальному та глобальному
              рівнях, створити незабутні спогади та багато иншого.
              Скаутинг допомагає кожному стати більш впевненою,
              відповідальною та всебічно розвиненою особистістю.",
      'en' => 'Scout organizations worldwide prioritize the safety and well-being of their members, and NOSU is no exception. Our Scout Leaders undergo special "Safe from Harm" training, developed and patented by the WOSM to guarantee a safe and supportive environment for all members of the Scout Movement in any activity. In Scouting, every member of the Organization gets the opportunity to gain valuable life skills, make lifelong friends, become a driver of change at local and global levels, create unforgettable memories, and much more. Scouting helps everyone become a more confident, responsible, and comprehensively developed person.'
    ],

  ],
];
