<?php
return [
  
    [
      "src" => "/images/world-scouting-organisation/photo1.jpg",
      "title" => [
        'ua' => "Місія ВОСР",
        'en' => ' Mission of WOSM'
      ],
      "text" => [
        'ua' => "Сприяння вихованню молоді через систему цінностей, засновану
                  на Скаутській Обіцянці та Законі. Через Скаутинг ми будуємо
                  кращий світ, де люди самореалізуються як особистості та
                  відіграють конструктивну роль у суспільстві.",
        'en' => "To promote the education of young people through a system
         of values based on the Scout Promise and Law. Through Scouting,
          we build a better world where people fulfil themselves as individuals
           and play a constructive role in society."
      ],
    ],
    [
      "src" => "/images/world-scouting-organisation/photo2.jpg",
      "title" => [
        'ua' => "Бачення ВОСР",
        'en' => 'WOSM Vision'
      ],
      "text" => [
        'ua' => "До 2033 року Бачення ВОСР полягає в тому, щоб стати найбільш
         надихаючим та інклюзивним молодіжним рухом у світі, який створює трансформаційний
          освітній досвід для кожної молодої людини, де б вона не жила.",
        'en' => "By 2033, WOSM's Vision is to be the world's most inspiring
         and inclusive youth movement creating transformative learning experiences 
         for every young person, everywhere."
      ],
    ],
    [
      "src" => "/images/world-scouting-organisation/photo3.jpg",
      "title" => [
        'ua' => "Історія Організації",
        'en' => ' History of the Organization'
      ],
      "text" => [
        'ua' => " Всесвітня Організація Скаутського Руху (ВОСР / WOSM /ˈwʊzəm/)
                  була створена в 1922 році і є найбільшою міжнародною
                  молодіжною організацією. ВОСР має 175 члени – Національні
                  Скаутські Організації, які разом налічують близько 57
                  мільйонів учасників.",
        'en' => "The World Organization of the Scout Movement (WOSM /ˈwʊzəm/)
         was established in 1922 and is the largest international youth organization. 
         WOSM has 175 member National Scout Organizations, which together have about 57 million members.  "
      ],
    ],
    [
      "src" => "/images/world-scouting-organisation/photo4.jpg",
      "title" => [
        'ua' => "Структура ВОСР",
        'en' => 'Structure of the WOSM'
      ],
      "text" => [
        'ua' => "ВОСР організована за регіональним принципом і має у своєму
                  складі Всесвітній Скаутський Комітет як виконавчий орган або
                  “правління” ВОСР, Всесвітню Конференцію як вищий законодавчий
                  орган та Всесвітнє Скаутське Бюро – секретаріат ВОСР.",
        'en' => "WOSM is organised on a regional basis and is composed of 
        the World Scout Committee as the executive body or ‘board’ of WOSM,
         the World Conference as the supreme legislative body and the World Scout Bureau
          as the secretariat of WOSM."
      ],
    ],
  ];