<?php
return [
  "page-title" => [
    'ukr' => "Більше про ВОСР",
    'en' => "More about WOSM",
  ],

  "meta-title" => [
    'ukr' => "Більше про ВОСР",
    'en' => 'More about WOSM'
  ],
  "meta-description" => [
    'ukr' => "Більше про ВОСР.",
    'en' => 'More about WOSM.'
  ],
  "main-title" => [
    'ukr' => "Всесвітня Організація Скаутського Руху",
    'en' => "World Organization of the Scout Movement",
  ],
  "sub-title" => [
    'ukr' => "Більше про ВОСР",
    'en' => "More about WOSM",
  ],
  "headquarters-title" => [
    'ukr' => " Штаб-квартира <br /> Скаутського Бюро",
    'en' => "Headquarters <br /> of the Scout Bureau",
  ],
  "headquarters-information-first" => [
    'ukr' => "Штаб-квартира Всесвітнього Скаутського Бюро знаходиться в
              Куала-Лумпурі, Малайзія, і має представництва в шести
              регіональних підрозділах. Кожен регіон дублює всесвітню структуру
              ВОСР та відповідно має Регіональний Скаутський Комітет,
              Регіональну Скаутську Конференцію та Регіональне Скаутське Бюро.",
    'en' => "The World Scout Bureau is headquartered in Kuala Lumpur, Malaysia,
     and has offices in six regional units. Each region duplicates the global 
     structure of WOSM and, accordingly, has a Regional Scout Committee, 
     a Regional Scout Conference and a Regional Scout Bureau.",
  ],
  "headquarters-information-second" => [
    'ukr' => "Україна разом з іншими країнами Європи входить до Європейського
              Регіону.",
    'en' => "Ukraine, along with other European countries, 
    is part of the Europe Region.",
  ],
  
];
