<?php
return [
  
    [
      "title" => [
        'ukr' => "Європейський регіон",
        'en' => 'Europe Region'
      ],
      "text" => [
        'ukr' => "Брюсель, Бельгія",
        'en' => "Brussels, Belgium"
      ],
    ],
    [
      "title" => [
        'ukr' => "Арабський Регіон",
        'en' => 'Arab Region'
      ],
      "text" => [
        'ukr' => "Каїр, Єгипет",
        'en' => "Cairo, Egypt"
      ],
    ],
    [
      "title" => [
        'ukr' => "Азійсько – Тихоокеанський регіон",
        'en' => 'Asia-Pacific Region'
      ],
      "text" => [
        'ukr' => "Маніла, Філіппіни",
        'en' => "Manila, Philippines"
      ],
    ],
    [
      "title" => [
        'ukr' => "АФРИКАНСЬКИЙ РЕГІОН",
        'en' => 'Africa Region'
      ],
      "text" => [
        'ukr' => "Найробі, Кенія",
        'en' => "Nairobi, Kenya"
      ],
    ],
    [
      "title" => [
        'ukr' => "Інтер – Американський регіон",
        'en' => 'Interamerica Region'
      ],
      "text" => [
        'ukr' => "Панама, Панама",
        'en' => "Panama City, Panama"
      ],
    ],
  ];