<?php
return [

  "page-title" => [
    'ukr' => "Скаути України",
    'en' => "Scouts of Ukraine",
  ],

  "meta-title" => [
    'ukr' => "Скаути України",
    'en' => 'Scouts of Ukraine'
  ],
  "meta-description" => [
    'ukr' => "Всеукраїнська молодіжна громадська організація заснована у 2007 році. Наша Місія – це сприяння вихованню молоді України за системою цінностей, заснованій на Скаутській Обіцянці та Скаутському Законі.",
    'en' => ''
  ],


  "open-world" => [
    'ukr' => "Відкрий світ українського Скаутингу!",
    'en' => "Discover Ukrainian Scouting!",
  ],
  "join-us" => [
    'ukr' => "Приєднатись <span> до нас</span>",
    'en' => "Join Us",
  ],
  "about-us-title" => [
    'ukr' => "Про нас",
    'en' => "About Us"
  ],
  "about-us-text" => [
    'ukr' => '<span class="about-scouts-text-bold">Скаути України</span> - це
    молодіжна громадська організація, що сприяє розвитку молодих
    людей через Скаутинг. Ми прагнемо виховувати лідерів та
    відповідальних громадян, надаючи можливості для пригод, навчання
    та самовдосконалення.',
    'en' => '<span class="about-scouts-text-bold">Scouts of Ukraine</span> - is a youth organization that aims to develop young people through Scouting.
We want to develop leaders and responsible citizens, giving them possibilities to study, 
have adventures, and self-improve.',
  ],
  "sc-ua-title" => [
    'ukr' => "Скаути україни",
    'en' => "Scouts of Ukraine"],
  "sc-ua-a" => [
    'ukr' => "Освітніх заходів",
    'en' => "Educational events"
  ],
  "sc-ua-b" => [
    'ukr' => "Країни - партнери",
    'en' => " Partner countries"
  ],
  "sc-ua-c" => [
    'ukr' => "Об'єднань в Україні",
    'en' => "Groups in Ukraine"
  ],
  "our-events-title" => [
    'ukr' => "Наші заходи",
    'en' => "Our events"
  ],
  "sc-review-title" => [
    'ukr' => "Відгуки про скаутінг",
    'en' => "Reviews"
  ],
  "invitation-title" => [
    'ukr' => "Запрошуємо стати <br /> Скаутом або Скаут-Лідером!",
    'en' => "Become a <br /> Scout or a Scout-Leader!"
  ],
  "invitation-text" => [
    'ukr' => "Членом Національної Організації Скаутів України може стати
            кожний, незалежно від віку, походження, раси, гендеру чи
            віросповідання!",
    'en' => "Anyone, regardless of age, background, race, gender,
     or religion, is welcome to become a member of the
      National Organization of Ukrainian Scouts!"
  ],
  "join-us-bottom" => [
    'ukr' => "Приєднатись до нас",
    'en' => "Join Us",
  ],
];
