<?php
return [
  [
    [
      "subclass" => "first",
      "text" => "",
      "photo" => "",
      "photo-alt" => "",
      "name" => "",
      "status" => ""
    ],
    [
      "subclass" => "",
      "text" => [
        "ukr" => "Для мене Скаутинг - це місце, де цікаво все: я знаходжу
                нових друзів, граю в активні ігри, дізнаюсь нове, подорожую
                та беру участь у таборах. А ще, я почала старанніше вчити
                англійську, бо вона потрібна на міжнародних івентах. Бути
                Скаутом захоплює!",
        "en" => "For me, Scouting is a place where everything is exciting: I make new friends, play active games, 
learn new things, travel, and participate in camps. I’ve also started learning English more diligently 
because it’s needed for international events. Being a Scout is inspiring!",
      ],
      "photo" => "./images/about-us/Base-1.png",
      "photo-alt" => [
        "ukr" => "Поліна Прик",
        "en" => "Polina Pryk"
      ],
      "name" => [
        "ukr" => "Поліна Прик",
        "en" => "Polina Pryk"
      ],
      "status" => [
        "ukr" => 'Скаут СО "Тотем"',
        "en" => 'Scout of "Totem"'
      ]
    ],
    [
      "subclass" => "second",
      "text" => "",
      "photo" => "",
      "photo-alt" => "",
      "name" => "",
      "status" => ""
    ]
  ],


  [
    [
      "subclass" => "first",
      "text" => "",
      "photo" => "",
      "photo-alt" => "",
      "name" => "",
      "status" => ""
    ],
    [
      "subclass" => "",
      "text" => [
        "ukr" => "Це дійсно унікальна можливість для саморозвитку та
                формування характеру. Я пишаюся дивовижними молодими людьми,
                які виросли з дітей моїх знайомих, що в НОСУ з дитинства.
                Мій син - у Скаутах, а дочка нещодавно стала Кабскаутом, і я
                не памʼятаю її щасливішою.",
        "en" => "It is truly a unique opportunity for self-development and character building. 
        I am proud of the amazing young people who have grown in NOSU. My son is a Scout and my
         daughter recently became a Cub Scout - I have never seen her happier.",
      ],
      "photo" => "/images/about-us/Base-2.jpg",
      "photo-alt" => [
        "ukr" => "Андрій Смиковський",
        "en" => "Andriy Smykovsky"
      ],
      "name" => [
        "ukr" => "Андрій Смиковський",
        "en" => "Andriy Smykovsky"
      ],
      "status" => [
        "ukr" => 'Батько дітей-Скаутів',
        "en" => 'Father of Scouts'
      ]
    ],

    [
      "subclass" => "",
      "text" => [
        "ukr" => 'В моєму патрулі - всі мої найкращі друзі! Я з нетерпінням
                чекаю кожної зустрічі, аби проводити час разом та
                дізнаватися нове.',
        "en" => 'Everyone in my patrol is my best friend! I 
        look forward to every meeting to spend time together and learn new things.'
      ],
      "photo" => "/images/about-us/Base-3.jpg",
      "photo-alt" => [
        "ukr" => 'Єсенія Пономаренко',
        "en" => 'Yeseniia Ponomarenko'
      ],
      "name" => [
        "ukr" => 'Єсенія Пономаренко',
        "en" => 'Yeseniia Ponomarenko'
      ],
      "status" => [
        "ukr" => 'Кабскаут СО "Асгард"',
        "en" => 'Cub Scout of "Asgard"'
      ]
    ],
    [
      "subclass" => "second",
      "text" => "",
      "photo" => "",
      "photo-alt" => "",
      "name" => "",
      "status" => ""
    ]
  ],


  [
    [
      "subclass" => "first",
      "text" => "",
      "photo" => "",
      "photo-alt" => "",
      "name" => "",
      "status" => ""
    ],
    [
      "subclass" => "",
      "text" => [
        "ukr" => 'На вихідних я завжди з посмішкою вирушаю до своєї Cкаутської
                групи, бо знаю, що на мене чекають. Популярний стереотип:
                "Скаутинг - це лише для дітей", однак мій досвід відкрив
                мені безцінні уроки, яких не змогли надати ані школа, ані
                університет, ані робота. Окрім цього, я відчуваю, що роблю
                внесок у формування майбутнього України — це надзвичайно
                важливо, особливо зараз. Сподіваюся, що все більше людей
                усвідомлюватимуть значущість цієї справи і приєднаються до
                нас.',
        "en" => "I head to my Scout group with a smile on my face, knowing
         they've been waiting. There's a common stereotype: 'Scouting is just
          for kids', but my experience has taught me invaluable lessons that neither
           school, university nor work can provide. I also feel that I'm helping to
            shape the future of Ukraine - something that's incredibly important right now.
             I hope that more people will realise the value of this mission and join us.",
      ],
      "photo" => "/images/about-us/Base-4.jpg",
      "photo-alt" => [
        "ukr" => "Анастасія Ратушняк",
        "en" => "Anastasiia Ratushnyak"
      ],
      "name" => [
        "ukr" => "Анастасія Ратушняк",
        "en" => "Anastasiia Ratushnyak"
      ],
      "status" => [
        "ukr" => 'Скаут-лідер',
        "en" => 'Scout-leader'
      ]
    ],
    [
      "subclass" => "second",
      "text" => "",
      "photo" => "",
      "photo-alt" => "",
      "name" => "",
      "status" => ""
    ]
  ],
];
