<?php
return [
  [
    "title" => [
      'ua' => "Наша Історія",
      'en' => 'Our history
'
    ],
    "text" => [
      'ua' => "Національну Організацію Скаутів України (НОСУ) засновано у
              2007 році. У 2008 році на 38-й Всесвітній Скаутській
              Конференції у Кореї НОСУ стала повноправним членом Всесвітньої
              Організації Скаутського Руху (далі – ВОСР).",
      'en' => "National Organization of Scouts of Ukraine (NOSU) was founded in 2007.
       At the 38th international Scout Conference in 2008, NOSU became a rightful member
        of The World Organization of the Scout Movement (WOSM)"
    ],
    'image' => 'about-us/photo-1.jpg',
    'url' => '/our-history'
  ],
  [
    "title" => [
      'ua' => "Місія",
      'en' => "Mission"
    ],
    "text" => [
      'ua' => "Наша Місія – це сприяння вихованню молоді України за системою
      цінностей, заснованій на Скаутській Обіцянці та Скаутському
      Законі. Через Скаутинг ми будуємо кращий світ, де люди
      самореалізуються як особистості та відіграють конструктивну
      роль у суспільстві.",
      'en' => "Our mission is to enhance the development of Ukrainian youth through the value system 
      based on the Scout Promise and the Scout Law. Through Scouting, we create a better world where 
      people can fulfil themselves as members of the community."
    ],
    'image' => 'about-us/photo-2.png',
    'url' => '/our-mission'
  ],
  [
    "title" => [
      'ua' => "Програма",
      'en' => "Programme"
    ],
    "text" => [
      'ua' => "Скаутська Молодіжна Програма є основою Скаутингу. Це
              відповідно організований, практичний навчальний процес для
              дітей та підлітків, спрямований на гармонійний та всебічний
              розвиток особистости задля досягнення свого найвищого
              потенціалу.",
      'en' => "National Youth Programme is the basis of Scouting. This is a carefully designed, 
      practical educational plan for children and young people, aimed at the full realization 
      and development of the personality."
    ],
    'image' => 'about-us/photo-3.jpg',
    'url' => '/our-mission'
  ],
  [
    "title" => [
      'ua' => "Скаутський Метод",
      'en' => "The Scout Method"
    ],
    "text" => [
      'ua' => "Скаутський метод – це унікальна система прогресивного
              розвитку, яка базується на 8 ключових елементах. Вони
              використовуються лише всі разом та сприяють повноцінному
              всебічному розвитку особистості у Скаутингу.",
      'en' => "The Scout Method is a unique system of progressive self-development 
      consisting of eight interrelated components. They are used together to ensure
       the full development of one's identity."
    ],
    'image' => 'about-us/photo-4.jpg',
    'url' => '/scout-method'
  ]
];
