<?php
return [
    [
      
      "title" => [
        'ukr' => "Обов’язок перед Богом",
        'en' => 'Duty to God'
      ],
      "text" => [
        'ukr' => " Цей принцип не має на меті нав‘язати певну релігію та
                  релігійні обовʼязки, як-от регулярне відвідування церкви
                  тощо. Обов’язок перед Богом - це про розвиток духовности,
                  духовних принципів, пошук віри у Бога чи у Вищу Істоту, а
                  також у визнанні вищих за людину сил. Важливий аспект
                  вищесказаного полягає у відносинах людини з духовними
                  цінностями життя. Невідʼємною частиною є повага до прав тих,
                  чиї вірування відрізняються.",
        'en' => "Adherence to spiritual principles, loyalty to the religion
         that expresses them, and acceptance of the duties resulting therefrom.
          An important aspect of this Scouting principle is a person's relationship
           with the spiritual values of life and their fundamental belief in a higher power.
            Fulfill your religious responsibilities and respect the rights of those
             whose beliefs differ from your own."
    ],
  ],
  [
      
    "title" => [
      'ukr' => "Обов’язок перед іншими",
      'en' => 'Duty to others'
    ],
    "text" => [
      'ukr' => " Вірність своїй країні, пропагування на місцевому,
                  національному та міжнародному рівні принципів
                  взаєморозуміння та співпраці. Участь у розвитку суспільства
                  з визнанням та повагою до гідности людства і цілісности
                  природного світу. Цей принцип спрямовує молоду людину до
                  відносин із суспільством і формує відповідальність перед
                  ним. Суспільство в цьому контексті має найширший сенс цього
                  слова та означає: сім’ю, місцеву громаду, країну і весь
                  світ, а також повагу до всього людства і до світу природи в
                  цілому.",
      'en' => "Loyalty to one’s country in harmony with the promotion of local,
       national, and international peace, understanding, and cooperation.
        Participation in the development of society with recognition and respect
         for the dignity of humanity and for the integrity of the natural world 
         This Scouting principle focuses on the individual's relationship with society
          and responsibility to it. Society is taken in the broadest sense of the word
           and includes family, local community, country and the world, as well as respect
            for all humanity and nature as a whole."
  ],
],
[
      
  "title" => [
    'ukr' => 'Обов’язок перед собою',
    'en' => 'Duty to self'
  ],
  "text" => [
    'ukr' => "Скаутський принцип, який нагадує про відповідальність людини
                  за розвиток свого потенціалу як найкращого втілення своїх
                  здібностей. Це означає прагнення до самовдосконалення і
                  відповідального ставлення до особистого розвитку. Скаути
                  вчаться встановлювати та досягати особисті цілі, виховуючи в
                  собі впевненість, незалежність та самодисципліну, які
                  служать фундаментом для успішного життя.",
    'en' => "A Scouting Principle that reminds of the individual's
     responsibility to develop one's potential to the best of one's ability.
      This means striving for self-improvement and taking responsibility
       for personal development. Scouts learn to set and achieve personal goals, 
       developing the confidence, independence and self-discipline 
       that serve as the foundation for a successful life."
],
],
];