<?php
return [
  [
    [
      "number" => "1",
      "title" => [
        'ua' => "Скаутська Обіцянка та Закон",
        'en' => 'The Scout Promise and Law'
      ],
      "text" => [
        'ua' => "Особисте добровільне зобов’язання дотримуватися набору
                      спільних цінностей, які є основою всього, що робить Скаут і
                      ким він хоче бути. Обіцянка та Закон займають центральне місце
                      в Скаутському методі.",
        'en' => " A personal voluntary commitment to a set of shared values, which is the foundation of everything a Scout does and a Scout wants to be. 
"
      ],
    ],
    [
      "number" => "2",
      "title" => [
        'ua' => "Навчання через справу",
        'en' => 'Learning by doing'
      ],
      "text" => [
        'ua' => "Використання практичних дій (реального життєвого досвіду) та
                      роздумів для сприяння безперервному навчанню та персональному
                      росту.",
        'en' => " The use of practical actions (real life experiences) and reflection(s) to facilitate ongoing learning and development.
. 
"
      ],
    ],
    [
      "number" => "3",
      "title" => [
        'ua' => "Система малих груп",
        'en' => 'Team system'
      ],
      "text" => [
        'ua' => "Використання малих груп (патрулів) як спосіб участи у
                      спільному навчанні з метою розвитку ефективної командної
                      роботи, міжособистісних навичок, лідерства, а також формування
                      почуття відповідальности та приналежности до групи.",
        'en' => " The use of small teams as a way to participate in collaborative learning, with the aim of developing effective team work, interpersonal skills, leadership as well as building a sense of responsibility and belonging. 
"
      ],
    ],
    [
      "number" => "4",
      "title" => [
        'ua' => "Залучення до громади",
        'en' => 'Community involvement'
      ],
      "text" => [
        'ua' => "Активне дослідження та відданість громаді та ширшому світові,
                      сприяння більшій вдячности та взаєморозумінню між людьми.",
        'en' => " Active exploration and commitment to communities and the wider world, fostering greater appreciation and understanding between people. 
"
      ],
    ],
  ],
  [
    [
      "number" => "5",
      "title" => [
        'ua' => "Символічна основа",
        'en' => 'Symbolic Framework'
      ],
      "text" => [
        'ua' => "Об’єднана структура тем і символів, що сприяє навчанню та
                      розвитку унікальної особистости Скаута.",
        'en' => "A unifying structure of themes and symbols to facilitate learning and the development of a unique identity as a Scout."
      ],
    ],
    [
      "number" => "6",
      "title" => [
        'ua' => "Підтримка дорослих",
        'en' => 'Adult support'
      ],
      "text" => [
        'ua' => "Дорослі сприяють і підтримують молодих людей у створенні
                      можливостей для навчання, і через культуру партнерства
                      перетворюють ці можливості на значущий досвід.",
        'en' => "Adults facilitating and supporting young people to create learning opportunities, and through a culture of partnership, turn these opportunities into meaningful experiences.
"
      ],
    ],
    [
      "number" => "7",
      "title" => [
        'ua' => "Особистісний розвиток",
        'en' => 'Personal progression'
      ],
      "text" => [
        'ua' => "Прогресивна навчальна подорож, зосереджена на мотивації та
                      стимулюванні людини до постійного прогресу через широкий
                      спектр освітньо-виховних заходів та матеріалів.",
        'en' => "A progressive learning journey focused on motivating and challenging an individual to continually develop, through a wide variety of learning opportunities. 
"
      ],
    ],
    [
      "number" => "8",
      "title" => [
        'ua' => "Природа",
        'en' => 'Nature'
      ],
      "text" => [
        'ua' => "Можливості навчання на свіжому повітрі, які сприяють кращому
                      розумінню та взаємозв’язку з навколишнім середовищем.",
        'en' => "Learning opportunities in the outdoors which encourage a better understanding of and a relationship with the wider environment.
. 
"
      ],
    ],
  ],
];
