<?php
return [
  "page-title" => [
    'ua' => "Скаутський метод",
    'en' => "The Scout method",
  ],

  "meta-title" => [
    'ua' => "Скаутський метод",
    'en' => 'The Scout method'
  ],
  "meta-description" => [
    'ua' => "Скаутський метод.",
    'en' => 'The Scout method.'
  ],

  "main-title" => [
    'ua' => "Скаутський метод",
    'en' => "The Scout method",
  ],
  "main-text" => [
    'ua' => "Скаутський Метод є унікальною системою прогресивного самовиховання.
              Він застосовує різні елементи, які підтримують мету та Принципи
              Скаутингу, і створює згуртовану та збалансовану систему для молодих
              людей, щоб вони могли відчути справжній потенціал Скаутингу в
              безпечному середовищі. ",
    'en' => "The Scout Method is a unique system of progressive self-education.
It employs various elements that support the aim and Principles of Scouting,
 creating a cohesive and balanced system for young people to experience
  the true potential of Scouting in a safe environment.",
  ],
  
  "elements-banner-link" => [
    'ua' => "/images/scouting-method/icons/scouting-method-diagram.svg",
    'en' => "/images/scouting-method/icons/scouting-method-diagram.svg",
  ],

  "scouts-promises-title" => [
    'ua' => "Скаутська Обіцянка",
    'en' => "The Scout Promise
",
  ],
  "scouts-promises-header" => [
    'ua' => "Скаутська обіцянка НОСУ:",
    'en' => "The Scout Promise of NOSU:",
  ],
  "scouts-promises-main-text" => [
    'ua' => '«Обіцяю зробити все від мене залежне, щоб з честю виконати свій
              обов’язок перед Богом і моєю країною, скрізь і повсякчас
              допомагати іншим та жити за Скаутським законом»',
    'en' => ' "I promise to do everything in my power to honor my duty to God and my country, to help others everywhere and at all times, and to live by the Scout Law.',
  ],
  "promises-additional-title" => [
    'ua' => "Обіцянка перед собою:",
    'en' => "A promise to oneself:",
  ],
  "scouts-promises-text-part" => [
    'ua' => " Молода людина складає Обіцянку не дорослому лідеру чи
                    своєму патрулю, а перед самим собою. Тим не менше,
                    потрібно пам’ятати, що протягом всього Скаутського життя
                    Скаут взаємодіє з командою однодумців – в патрулі, а отже,
                    присутність членів патруля, їхня підтримка та допомога в
                    процесі підготовки до складання Обіцянки є важливим. Кожен
                    Скаут проголошує Обіцянку під час урочистої посвяти в колі
                    друзів свого формування, таким чином засвідчує готовність
                    дотримуватись та жити за Скаутськими принципами та
                    Скаутським законом.",
    'en' => "The young person is not making a promise to an adult
     leader or to his or her patrol, but to themselves. 
     However, it must be remembered that throughout his Scouting life,
      a Scout interacts with a team of like-minded people - his patrol -
       and therefore the presence of patrol members, their support and assistance
        in the process of preparing to take the Promise is important.
         Each Scout recites the Promise during a solemn initiation with the
          friends of his unit, thus demonstrating his or her willingness to follow 
          and live by the Scouting principles and the Scout Law.",
  ],
  "scouts-law-title" => [
    'ua' => "Скаутський Закон",
    'en' => "The Scout Law",
  ],
  "scouts-law-text" => [
    'ua' => "Скаутський закон – єдиний та складається з десяти пунктів, кожен з
            яких сформульований коротко, але має глибоку суть. Текст Закону
            може несуттєво відрізнятися в різних Національних Скаутських
            Організаціях, що обумовлено специфікою культури і традицій країни.
            Однак, все одно в основі кожного формулювання лежить найперший
            Закон, сформульований засновником Скаутингу – лордом
            Бейден-Поуеллом.",
    'en' => "There is only one Law and it consists of ten points, each of which
     is explained briefly, but has a very deep meaning. Its wording may vary 
     from one National Scout Organization to another, depending on the culture
      and traditions of the country, but it is based on the Law formulated by the
       Founder of Scouting, Lord Baden-Powell.",
  ],
  "scouts-law-list-text" => [
    'ua' => " Кожен пункт Закону сформульований коротко, але він має дуже
                глибоку суть:",
    'en' => "Every point of the Law is explained briefly, but it has a very deep meaning:",
  ],
  "scouts-principles-title" => [
    'ua' => "Скаутські Принципи",
    'en' => "The Principles of the Scout Movement",
  ],
  "scouts-principles-text" => [
    'ua' => " В Скаутингу все символьно та тісно взаємопов’язано, саме тому
              три Скаутські принципи відображені в Скаутській емблемі (три
              пелюстки лілії) та в Скаутському знакові (три прямі пальці).
              Скаутинг залишається єдиним цілим, зокрема завдяки тому, що
              Скаутські принципи є неподільними та застосовуються разом.",
    'en' => "In Scouting, everything is symbolic and closely connected,
 which is why the Scouting Principles are reflected in the Scout Emblem 
 (three lily petals) and the Scout Sign (three straight fingers). 
 Scouting remains united, in part because the Scouting Principles 
 are indivisible and applied together.",
  ],
  "promises-text-part-first" => [
    'ua' => 'Скаутська Обіцянка – це особисте та соціальне зобов’язання,
                яке молода людина дає на початку своєї Скаутської подорожі.
                Оскільки кожний Скаут у всьому світі дає подібну обіцянку,
                вона підтримує відчуття єдности та знаменує перший крок до
                самовиховання та відкриття Скаутського методу. Член
                Національної Організації Скаутів України проголошує Скаутську
                Обіцянку, зафіксовану Статутом організації.',
    'en' => 'The Scout Promise is a personal and social commitment
     that a young person makes at the beginning of their Scouting journey.
      As every Scout around the world makes a similar promise, it promotes 
      a sense of unity and marks the first step towards self-education and 
      discovery of the Scout Method. A member of the National Organization of Scouts of Ukraine
       proclaims the Scout Promise, which is fixed in the Constitution of the organization.',
  ],
  "promises-text-part-second" => [
    'ua' => 'ПРИМІТКИ: Член Національної Організації Скаутів України проголошує Скаутську Обіцянку, 
    зафіксовану Статутом Організації. Вона є адаптованим перекладом тексту
     Скаутської обіцянки з Конституції Всесвітньої Організації Скаутського Руху.',
    'en' => "NOTES: A member of the Scouts of Ukraine proclaims the Scout Promise,
     which is fixed in the Organization's Constitution. It is an adapted translation
      of the Scout Promise from the Constitution of the World Organization of the Scout Movement.",
  ],
  "promises-text-part-third" => [
    'ua' => 'Рішення про складання Скаутської обіцянки може прийняти
                винятково та особа, яка прагне приєднатись до Скаутського
                Руху.',
    'en' => "The decision to take the Promise can only be made by the person who wants to join the Scout Movement.",
  ],
];
