<?php
return [
  [
    "item" => [
      'ukr' => "Честі Скаута слід довіряти",
      'en' => "A Scout’s honor is to be trusted"
    ]
  ],
  [
    "item" => [
      'ukr' => "Скаут – вірний",
      'en' => "A Scout is loyal
"
    ]
  ],
  [
    "item" => [
      'ukr' => "Обов’язок Скаута бути корисним та допомагати іншим",
      'en' => "A Scout's duty is to be useful and to help others"
    ]
  ],
  [
    "item" => [
      'ukr' => "Скаут дружній з усіма та братерський зі Скаутами",
      'en' => "A Scout is a friend to all and a brother to every other Scout"
    ]
  ],
  [
    "item" => [
      'ukr' => "Скаут – ввічливий",
      'en' => "A Scout is courteous"
    ]
  ],
  [
    "item" => [
      'ukr' => "Скаут – друг природи",
      'en' => "A Scout is a friend of nature"
    ]
  ],
  [
    "item" => [
      'ukr' => "Скаут уважний до настанов своїх батьків, патрульного лідера та Скаут-лідерів, без зайвих питань",
      'en' => "A Scout is attentive to the instructions of his parents, Patrol Leader and Scout Leaders, without question"
    ]
  ],
  [
    "item" => [
      'ukr' => "Скаут усміхається і наспівує за будь-яких обставин",
      'en' => "A Scout smiles and sings under all circumstances"
    ]
  ],
  [
    "item" => [
      'ukr' => "Скаут – ощадливий",
      'en' => "A Scout is thrifty"
    ]
  ],
  [
    "item" => [
      'ukr' => "Скаут чистий думками, словами та діями",
      'en' => "A Scout is clean in thought, word and deed"
    ]
  ],
];


















