<?php
return [

  [
    "src" => "./images/our-events/photo1.JPG",

    "title" => [
      'ukr' => "Тренінги",
      'en' => ''
    ],
    "texts" => [
      [
        "text" => [
          'ukr' => "Наші тренінги орієнтовані на Скаутів та Скаутських лідерів
                      на різних етапах їхньої Скаутської подорожі та розроблені
                      таким чином, щоб задовольнити потреби й інтереси членів
                      різного віку та сприяти отриманню Скаутських умінь. Від
                      домедичної допомоги до лідерських навичок і комунікації, ми
                      пропонуємо винятковий освітній підхід до навчання, який
                      виходить за рамки традиційного навчання в класі. НОCУ
                      створює інклюзивне середовище для ефективного освоєння нових
                      навичок, необхідних для особистого зростання, дозволяючи
                      кожному розвиватися власним темпом.",
          'en' => "Our training sessions are aimed at Scouts and Scout leaders
           at different stages of their Scouting journey and are designed to meet
            the needs and interests of members of all ages and to help them develop
             their Scouting skills. From first aid to leadership and communication skills,
              we offer an exceptional educational approach to learning that goes beyond 
              the traditional classroom. NOSU creates an inclusive environment for
               effective learning of new skills necessary for personal growth,
                allowing everyone to develop at their own pace."
        ],
      ],
    ],
  ],

  [
    "src" => "./images/our-events/photo2.JPG",

    "title" => [
      'ukr' => "Онлайн-заходи",
      'en' => ''
    ],
    "texts" => [
      [
        "text" => [
          'ukr' => " У сучасну епоху цифрових технологій ми усвідомлюємо
                      важливість залишатися на зв’язку. Ми надаємо гнучкі шляхи
                      навчання, що задовольняють запити наших членів – як юних,
                      так і дорослих Скаутів. Серед них багатогранні інтерактивні
                      воркшопи, вебінари та віртуальні зустрічі для учасників
                      різного віку. Ці мережеві сходини можуть проводитися як
                      НОСУ, так і бути частиною заходів Всесвітнього Скаутингу, та
                      охоплювати різноманітні теми. Такі онлайн-заходи, як
                      Джемборі в Інтернеті – JOTA-JOTI  також надають платформу
                      для Скаутів з різних країн та вікових груп, аби ділитися
                      досвідом, обмінюватися ідеями та вчитися один в одного. Це
                      сприяє зміцненню почуття згуртованости та приналежности до
                      єдиного Руху, навіть коли ми не можемо зустрітися особисто.",
          'en' => "In today's digital age, we recognise the importance of staying
           connected. We provide flexible learning pathways that meet the needs of 
           our members - both young and adult Scouts. These include multifaceted
            interactive workshops, webinars and virtual meetings for participants
             of all ages. These networking events can be hosted by NOSU or as part
              of World Scouting events and cover a variety of topics. Online events
               such as the Jamboree on the Internet - JOTA-JOTI also provide a platform
                for Scouts from different countries and age groups to share experiences,
                 exchange ideas and learn from each other. This helps to strengthen the
                  sense of cohesion and belonging to a single Movement, even when 
                  we cannot meet in person. 
"
        ],
      ],
    ],
  ],

  [
    "src" => "./images/our-events/photo3.jpg",

    "title" => [
      'ukr' => "Міжнародні заходи",
      'en' => 'International events'
    ],
    "texts" => [
      [
        "text" => [
          'ukr' => "Ми беремо активну участь у міжнародних заходах, які сприяють
                      міжкультурному обміну та співпраці між Скаутами усіх вікових
                      секцій з різних куточків планети. Наші інтернаціональні
                      події є інклюзивними та задовольняють різноманітні інтереси
                      наших членів, пропонуючи релевантні активности для дітей,
                      молодих людей та дорослих лідерів. Саме завдяки таким
                      заходам за кордоном українські Скаути мають змогу формувати
                      дружбу на все життя, дізнаватися про особливости инших
                      держав та розвивати глобальну перспективу. Єдність нашого
                      Руху відкриває нашу схожість зі Скаутами інших країн, але
                      також показує їм різноманітність, а отже, вчить пошані та
                      розумінню відмінностей.",
          'en' => "We are actively involved in international events that promote 
          intercultural exchange and cooperation between Scouts of all ages from 
          all over the world. Our international events are inclusive and cater to
           the diverse interests of our members, offering relevant activities for
            children, young people and adult leaders. It is through these events 
            abroad that Ukrainian Scouts have the opportunity to form lifelong friendships,
             learn about the peculiarities of other countries and develop a global perspective. 
             The unity of our Movement reveals our similarities with Scouts in other countries,
              but also shows them our diversity, and thus teaches them respect 
              and understanding of differences.
"
        ],
      ],
    ],
  ],

  [
    "src" => "./images/our-events/photo4.jpg",

    "title" => [
      'ukr' => "Табори",
      'en' => 'Camps'
    ],
    "texts" => [
      [
        "text" => [
          'ukr' => "Табори є невідʼємною частиною Скаутингу та функціонування
                      Скаутських груп. Вони дозволяють учасникам безпосередньо
                      втілити в життя один з елементів Скаутського методу –
                      природу, а також навчитися незалежности та самостійности.
                      Табори зазвичай тривають від 7 до 14 днів і проводяться на
                      природі – у лісі, в горах або біля водойм. Впродовж цього
                      часу таборів Скаути навчаються самостійно ставити намети,
                      готувати їжу та здобувати нові навички. Також діти можуть
                      підтвердити знання та отримати нашивки за проходження
                      Скаутських випробувань. Кожен табір має свої особливости та
                      відповідає певній тематиці, що дозволяє дітям розвиватись в
                      різних напрямках. Літні табори зазвичай містять
                      скелелазіння, каякінг, сплави на байдарках, творчі
                      майстер-класи тощо. Зимові табори можуть пропонувати такі
                      види розваг, як катання на лижах та сноубордах.",
          'en' => "Camps are an integral part of Scouting and the functioning of Scout groups.
           They allow participants to directly experience one of the elements of the 
           Scouting method - nature - and to learn independence and self-sufficiency.
            Camps usually last from 7 to 14 days and are held outdoors: in the woods,
             mountains or near water. During these camps, Scouts learn how to pitch tents,
              cook and acquire new skills. Children can also confirm their knowledge and 
              receive badges for passing Scout challenges. Each camp has its own peculiarities
               and corresponds to a specific theme, which allows children to develop
                in different directions. Summer camps usually include rock climbing, kayaking,
                 canoeing, creative workshops, etc. Winter camps may offer activities 
                 such as skiing and snowboarding.
"
        ],
      ],
    ],
  ],
];