<?php
return [

  "main-title" => [
    'ukr' => "Наші заходи",
    'en' => "Our events",
  ],
  "main-text" => [
    'ukr' => "Ми організовуємо різноманітні та цікаві події для наших членів
              різного віку, щоб вони могли вчитися, розвиватися та спілкуватися.
              Наші заходи ретельно розроблені, щоб надихати, кидати виклик та
              розвивати навички Скаутів, як більш юних, так і старших. Ми
              пропонуємо унікальний досвід та можливості, які залишають
              довготривалий вплив на наших членів. У цьому розділі ми раді
              поділитися з вами деталями наших найпопулярніших категорій заходів:
              Тренінги, Онлайн-заходи та Міжнародні заходи, які розраховані на
              різні вікові групи, включаючи дітей, молодих людей та дорослих.",
    'en' => "We organise varied and exciting events for our members of all ages to learn, 
    develop and socialise. Our events are carefully designed to inspire, challenge 
    and develop the skills of Scouts young and old. We provide unique experiences
     and opportunities that leave a lasting impact on our members. 
     In this section you will find details of our most popular event
      categories: Training, Online Events and International Events, 
      designed for different age groups, including children, young people and adults.",
  ],
  "additional-text" => [
    'ukr' => "Хочеш долучитись? Розпочни свою Скаутську подорож сьогодні та
                відкрий безмежні <br> можливості, що вже чекають на тебе!",
    'en' => "Want to join? Start your Scouting journey today and discover
the endless <br> possibilities that are waiting for you",
  ],
  
  "join-btn" => [
    'ukr' => "Приєднатись до нас",
    'en' => "Join us",
  ],
  
  
];
