<?php
return [
  'logo' =>  [
    'en' => '/images/logo_header_en.svg',
    'ua' => '/images/logo-heder.svg'
  ],
  'join' => [
    'en' => 'Join us',
    'ua' => 'Приєднатися'
  ],
  'donation' =>  [
    'en' => 'Donation',
    'ua' => 'Задонатити'
  ],
  'donation' =>  [
    'en' => 'Donation',
    'ua' => 'Задонатити'
  ],
  'active-lang' => [
    'en' => "English",
    'ua' => 'Українська'
  ]
];
