<?php
return [
  [
    'header' => [
      'en' => 'About Us',
      'ukr' => 'Про нас'
    ],
    'links' => [
      [
        'link' => './our-history',
        'title' => [
          'en' => 'History',
          'ukr' => 'Наша історія'
        ]
      ],
      [
        'link' => './our-mission',
        'title' => [
          'en' => 'Mission',
          'ukr' => 'Наша місія'
        ]
      ],
      [
        'link' => './scout-method',
        'title' => [
          'en' => 'Method',
          'ukr' => 'Скаутський Метод'
        ]
      ],
      [
        'link' => './our-team',
        'title' => [
          'en' => 'Team',
          'ukr' => 'Команда'
        ]
      ]
    ]
  ],

  [
    'header' => [
      'en' => 'Activities',
      'ukr' => 'Діяльність'
    ],
    'links' => [
      [
        'link' => './our-mission#our-program',
        'title' => [
          'en' => 'Programme',
          'ukr' => 'Наша програма'
        ]
      ],
      [
        'link' => './help-ukrainians',
        'title' => [
          'en' => 'Projects',
          'ukr' => 'Проєкти'
        ]
      ],
      [
        'link' => './our-events',
        'title' => [
          'en' => 'Events',
          'ukr' => 'Заходи'
        ]
      ]
    ]
  ],
  [
    'header' => [
      'en' => 'World Scouting',
      'ukr' => 'Всесвітній Скаутинг'
    ],
    'links' => [
      [
        'link' => './world-scouting',
        'title' => [
          'en' => 'WOSM',
          'ukr' => 'ВОСР'
        ]
      ],
      [
        'link' => './scouting-history',
        'title' => [
          'en' => 'History of Scouting',
          'ukr' => 'Історія Скаутингу'
        ]
      ]
    ]
  ]
];
